### ISSUE TITLE
[BUG] Weird scrollbar on note preview

### ISSUE THREAD

**Issue by mfxarc** [org-roam/org-roam-ui#103]
When I double click on a note, a side panel shows up with preview of the file, but It has weird scrollbars on both bottom and right.

**To Reproduce**
1. Double click on a note

**Expected behavior**
Side panel without scrollbars

**Screenshots**
![1633992305](https://user-images.githubusercontent.com/91107012/136864544-6fc6d4e1-ce96-41ab-8742-57f204da2074.png)

**What browser were you using?**
Tested first with Chromium and after with Min browser, but the bug happen on both.

**Comment by ThomasFKJorna** [comment]
This might not completely fix it as I don't have the time to look into it, but hopefully it's somewhat better. Check the latest commit

**Comment by mfxarc** [comment]
Thanks! It seems to be fixed now
