### ISSUE TITLE
[MINOR] Preview a node should only show that node, not the whole file

### ISSUE THREAD

**Issue by ThomasFKJorna** [org-roam/org-roam-ui#106]
**Have you checked whether this feature is not already on the [project board](https://github.com/org-roam/org-roam-ui/projects/2)?

Yes

**Is your feature request related to a problem? Please describe.**

Atm when you click on a node that is not a main file note, you just get taken to the preview of the main file. This is somewhat confusing as only the title of the preview window will change, but the text stays the same.

**Describe the solution you'd like**
Only show the current node, not the entire file. Just include a link at the top to either the parent or the file node when that setting is enabled.

**Describe alternatives you've considered**

**Additional context**

**Comment by wztdream** [comment]
Is there any progress of this bug?

**Comment by meedstrom** [comment]
Seems easy™in principle, where's the code that chooses what text to fill into the preview? I have no familiarity with the codebase, but presumably a function reads a file's content, and you could fork off an alternative path based on a boolean setting (just for testing), to read only a subtree instead, and proceed as normal.
