### ISSUE TITLE
Is there a plan to put this package on Melpa

### ISSUE THREAD

**Issue by linwaytin** [org-roam/org-roam-ui#112]
I'm just wondering if there is a plan to put this package on Melpa, since this is the preferred way for me to install packages.

Thanks for this great package!

**Comment by ThomasFKJorna** [comment]
There now is an open pull request for this! https://github.com/melpa/melpa/pull/7784

**Comment by memeplex** [comment]
I'm glad you obsoleted the orui- version of the functions. There are a couple of references yet:

https://github.com/org-roam/org-roam-ui/blob/ea947c6987708757ca41e8fafb80b2dacb570574/org-roam-ui.el#L72

https://github.com/org-roam/org-roam-ui/blob/ea947c6987708757ca41e8fafb80b2dacb570574/org-roam-ui.el#L168

**Comment by ThomasFKJorna** [comment]
Ah thanks for spotting that!

**Comment by ThomasFKJorna** [comment]
It's now on Melpa!
