### ISSUE TITLE
[MINOR] Expand local node and all of it's subnodes

### ISSUE THREAD

**Issue by harshasomisetty** [org-roam/org-roam-ui#115]
**Have you checked whether this feature is not already on the [project board](https://github.com/org-roam/org-roam-ui/projects/2)?**

Yes

**Is your feature request related to a problem? Please describe.**
I have various subjects in my org roam db, and I want do expand a subject in its entirety and see all the child nodes from a subject root

**Describe the solution you'd like**
After selecting my subject local node, I have a view of only direct children. I want an option that allows me to see all second-degree relations as well.

**Describe alternatives you've considered**
Currently, I can manually go through each child and show that child's relations as well, but this takes too long

**Comment by ThomasFKJorna** [comment]
I've been meaning to add this the foundation is there, I just didn't know how to do it UI wise although I've got an idea now.
How many levels, at most, do you think you would like to see at a time? 3,4? I think any more than that and you're showing the complete graph.

**Comment by harshasomisetty** [comment]
Yes it works, but would it be possible to delete local nodes so the tree doesn't expand into sections I'm not interested in? 

For example, I have a home file that links to say, Operating systems, and also to Statistical Analysis. I only want to see the graph for operating systems, but if I do the filter option on the OS node, it goes into the home node, and then to the rest of my graph

**Comment by ThomasFKJorna** [comment]
Great idea! I've just added the option, but it probably does not completely work like you would expect as it's pretty difficult to make work completely predictably with non-tree-like graphs (which loop back on itself).
Also works weirdly when you "remove" the root node (you're only left with the root node). I need to figure out a good way to show which nodes are the root nodes.

It will now not search down a path when you exclude it, which should work for most cases.
