### ISSUE TITLE
[BUG] Preview sends back an error for backlinks without note

### ISSUE THREAD

**Issue by RobinKD** [org-roam/org-roam-ui#118]
**Describe the bug**
For any file containing underscores in its name, there is an error an preview doesn't work.
I suppose it is a problem of Org/HTML handling _ as a special character.

**To Reproduce**
Simply trying to preview any node for which the filename has underscores.

**Expected behavior**
The preview shows the content of the file

**Screenshots**
The result I get is something like that :
![Screenshot_20211016_221027](https://user-images.githubusercontent.com/28922613/137600975-63773eb7-10c4-4b8c-88d9-81cf341482d5.png)

**What browser were you using?**
Firefox

**Comment by ThomasFKJorna** [comment]
Hmm I'm not sure that that's the exact issue, I have a node here with an underscore which works fine.
<img width="995" alt="Screenshot 2021-10-16 at 22 18 14" src="https://user-images.githubusercontent.com/21983833/137601147-6eb91802-1e2c-4f71-aa73-53b76752abbd.png">

**Comment by ThomasFKJorna** [comment]
What's the full name of your file/node?

**Comment by ThomasFKJorna** [comment]
Great to hear! Yes I still need to fix that, thanks for pointing it out!

**Comment by RobinKD** [comment]
Thanks, keep up the good work! This is an amazing package

**Comment by jason--liu** [comment]
I still have the same problem on the latest branch. @tefkah 
![image](https://user-images.githubusercontent.com/8001473/183617864-a1c436df-8ee9-4c99-81e0-8b13670fa78d.png)
