### ISSUE TITLE
[MINOR] Filter by subdirectory tags

### ISSUE THREAD

**Issue by harshasomisetty** [org-roam/org-roam-ui#119]
**Have you checked whether this feature is not already on the [project board](https://github.com/org-roam/org-roam-ui/projects/2)?**

No

**Is your feature request related to a problem? Please describe.**
Org roam v2 lets us put notes into subdirectories, which acts like mini tags. I want to be able to filter on these tags as well in ui mode

**Describe the solution you'd like**
Have a drop down of all the subdirectories in the original org roam directory, then depending on which folders are selected, only graph the nodes in those folders.

**Comment by harshasomisetty** [comment]
Just following up on this, would it be possible to implement this now? Should be pretty easy now with the "Tag Filters" menu, it would be a matter of another input for subdirectories, or (unideally) in the same input as the blacklist filters

**Comment by ThomasFKJorna** [comment]
I'll try to get this done soon, i have a need for it as well atm, expect it in one or two days!

**Comment by harshasomisetty** [comment]
Ah awesome, looking foward to it!

**Comment by harshasomisetty** [comment]
Sorry for bugging you but any update?

**Comment by ThomasFKJorna** [comment]
Hey man, sorry that it took so long, this had more edge-cases than I initially thought and was busy with other things. It should work with the next commit, give it a whirl!

**Comment by Elilif** [comment]
@tefkah  In my test, tags in  the directory allowlist will filter all nodes, and tags in the directory blocklist will do nothing. It seems that something is wrong.
