### ISSUE TITLE
Org-roam-ui seems frozen

### ISSUE THREAD

**Issue by maikol-solis** [org-roam/org-roam-ui#12]
First kudos to the devs for making possible this new package. 

Today I installed it, and once I entered to http://127.0.0.1:35901/ I observed a frozen ball of nodes without any connections, 

![image](https://user-images.githubusercontent.com/4078489/127751926-ec6b9023-701f-48ce-a9c8-2572cca86971.png)

If I click or try to drag any of the nodes, they simply disappear

![image](https://user-images.githubusercontent.com/4078489/127751940-a4b2f0a9-547b-4afb-9721-85f0470bb237.png)

I can help to debug this problem if you give some instructions. 

Best

**Comment by ThomasFKJorna** [comment]
Hi! I've had something like this happen a couple of times as well, and it usually has something to do with a link that doesn't work right. Could you check the console (Ctrl+Shift+I) and see if it says something about links missing?

**Comment by maikol-solis** [comment]
Yes it was that. Some link was missing in one of my files. I wrote this link 
```
[[id:20210111T174410][My note]]
```
but this note does not exist in the db.

![image](https://user-images.githubusercontent.com/4078489/127752162-c80d21fe-685f-4bb6-b991-1e0c50768afd.png)

I solve the issue following these steps: 

1. Remove the broken links
2.  Sync the database 
3. Update all the IDs with ` (org-id-update-id-locations (org-roam--list-all-files))`

![image](https://user-images.githubusercontent.com/4078489/127752220-b4889fe1-5421-49e7-a76f-78f6ee4e50e7.png)


Maybe `orui` could warn in the future to the user if that happens to see exactly which are the malicious links. 

I will close the issue. 

Thanks for the help.
