### ISSUE TITLE
[ENH] unset the color for a tag

### ISSUE THREAD

**Issue by kebairia** [org-roam/org-roam-ui#123]
There is no option to disable the color that you set for a tag.
here i set the **_red_** color the the tag **server**, but there is no way to undo that

![2021-10-17-1634504509_891x366](https://user-images.githubusercontent.com/3621146/137644951-025cf6c9-39f5-451f-955a-6886fa5e8952.png)

**Comment by ThomasFKJorna** [comment]
Ah yeah I noticed that as well, will add it soon! For now you can unset it in the "Tag Colors" panel under "Filter", sorry for the inconvenience!

**Comment by ThomasFKJorna** [comment]
Fixed
