### ISSUE TITLE
[ENH] Browser function

### ISSUE THREAD

**Issue by deb75** [org-roam/org-roam-ui#128]
Hello,

Currently my `emacs` browser settings are as follow : 
```elisp
(setq browse-url-browser-function 'eww-browse-url)

;; (setq browse-url-firefox-program local-browse-url-firefox-program
;;       browse-url-browser-function 'browse-url-firefox
;;       browse-url-new-window-flag nil
;;       browse-url-firefox-new-window-is-tab t)
```

When I run `org-roam-ui-mode`, it first opens a *eww buffer, then I hiet `&` and it opens it in another external browser.

However, it seems that `org-roam` does not follow me when I click on the browser graph node.

Would it be possible to customize the browser that `org-roam-ui-mode` calls ?

Regards

**Comment by ThomasFKJorna** [comment]
You already can! Use `(setq org-roam-ui-browser-function #'eww-browse-url)`

**Comment by deb75** [comment]
Thanks !

I have trouble setting with another browser.

Which browser is known to perform best with `orui` ?

With the setting :
```elisp
(setq browse-url-browser-function 'browse-url-generic)
(setq browse-url-generic-program "c:/path/to/chrome.exe")
```

I receive the error : 
```
start-process: Spawning child process: Invalid argument
```

It also happens on other links. So it is not specifically `orui` related. Does it happen for you ? (I am on windows 10)

**Comment by deb75** [comment]
Thanks.

I noticed that in the sidebar, the `cite:myref` links are not clickable, a forbidden icon appears. But in the video demonstration, it looks like on can follow the reference links.

The reference links do appear in the graph itself, if I click on them, the side bar opens, but displays :
```
<!DOCTYPE html> <html><head> <title>500 Internal Error</title> </head><body> <h1>500 Internal Error</h1> <p>Internal error when handling this request.</p> <pre>error: (file-missing Opening input file No such file or directory d:/xxx/yyy/org-roam/myref) </pre> </body></html>
```

but in the org file, I can open the pdf file (myref.pdf) with `C-c C-o`.

Do I miss something ?

Regards
