### ISSUE TITLE
Error on save: (void-function org-roam-ui)

### ISSUE THREAD

**Issue by shaunsingh** [org-roam/org-roam-ui#13]
Hi, thanks for the awesome package! 

Whenever I'm saving an org roam file, I'm getting 
```
Error (after-save-hook): Error running hook "org-roam-ui--on-save" because: (void-function org-roam-ui)
```
![image](https://user-images.githubusercontent.com/71196912/127752829-c36221ec-5623-4c50-b3a4-50860e68d6f4.png)

The graph itself is still updated

**Comment by ThomasFKJorna** [comment]
Huh, good call, for some reason there was a function call to (org-roam-ui) there, which is not a function. I just pushed a fix (just removing that function), should work now!

**Comment by shaunsingh** [comment]
Works, thanks once again
