### ISSUE TITLE
[MAJOR] Add special type of links using the PROPERTIES drawer

### ISSUE THREAD

**Issue by lytex** [org-roam/org-roam-ui#132]
**Have you checked whether this feature is not already on the [project board](https://github.com/org-roam/org-roam-ui/projects/2)?**

Yes

**Is your feature request related to a problem? Please describe.**
I want to give semantic meaning to the links. For example, if I'm joining a big, existing team, I want to create relationships like "John is Mike's boss" and "Angela works with Peter", and visualize these relationships (for example by coloring each type of link with a different type of color) so that the organizational chart emerges from individual links
Another use case is visualize a set of tasks and their dependencies

**Describe the solution you'd like**
As per this [org-roam issue](https://github.com/org-roam/org-roam/issues/1317) links inside an PROPERTIES drawer will not be considered as backlinks, which makes them perfect to declare a new type of link/backlink independent from all the other regular links
I think that coloring each type of link with one color and maybe using the same color for all nodes is a good starting point, another interesting implementation is drawing a small box with the type of relationship (see, for example [trillium](https://github.com/zadam/trilium/wiki/Relation-map) implements multiple types of links)

**Comment by shunlog** [comment]
@lytex I think this is the relevant discussion: [https://github.com/org-roam/org-roam-ui/discussions/25](https://github.com/org-roam/org-roam-ui/discussions/25). If you agree, maybe close the issue?

**Comment by lytex** [comment]
Yes, it's the same discussion, however this implementation is significantly different from the other one.
I'm closing this issue and doing a comparison in #25
