### ISSUE TITLE
[BUG] Crash on previewing table.el tables

### ISSUE THREAD

**Issue by Game4Move78** [org-roam/org-roam-ui#133]
**Describe the bug**
Table.el causes org-roam-ui to crash in the browser.

**To Reproduce**
+----------------------------------------------+
|             Feature Description              |
+----------------------------------------------+
|# Basic Blocks                                |
+----------------------------------------------+
|# Branches                                    |
+----------------------------------------------+
|# Divergent Instr.                            |
+----------------------------------------------+
|# Instrs. in Divergent Regions                |
+----------------------------------------------+
|(# instr. in Divergent regions)(#total instr.)|
+----------------------------------------------+
|# Divergent regions                           |
+----------------------------------------------+
|# Intrs                                       |
+----------------------------------------------+
|# Floating point instr.                       |
+----------------------------------------------+
|Avg. ILP per basic block                      |
+----------------------------------------------+
|(#integer instr.)/(#floating point instr)     |
+----------------------------------------------+
|# integer instr.                              |
+----------------------------------------------+
|# Math built-in func.                         |
+----------------------------------------------+
|Avg. MLP per basic block                      |
+----------------------------------------------+
|# loads                                       |
+----------------------------------------------+
|# stores                                      |
+----------------------------------------------+
|# loads that are independent of the coursening|
|direction                                     |
+----------------------------------------------+
|# barriers                                    |
+----------------------------------------------+

**Expected behavior**
Table displays, but the note can only be previewed if all table.el tables are removed.

**Screenshots**

![image](https://user-images.githubusercontent.com/83040764/138922461-0e440cee-1981-456b-8195-1746647d3157.png)
![image](https://user-images.githubusercontent.com/83040764/138922766-5ff45e46-9429-4393-b6d8-aebd43ba1736.png)

**What browser were you using?**
Firefox
**Additional context**
Spacemacs v.0.3 with GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-10-09

**Comment by rasendubi** [comment]
@Game4Move78 I’ve updated #135. Please take a look

**Comment by Game4Move78** [comment]
> @Game4Move78 I’ve updated #135. Please take a look

Works perfectly.

**Comment by rasendubi** [comment]
Great! @ThomasFKJorna would you like to merge #135?

**Comment by ThomasFKJorna** [comment]
This has been merged, thanks @rasendubi for being so pro-active! 

As to the build process: for now you can just either include the build or I will build it. I need to set up some kind of CD but for that I need admin access to the org-roam org, been meaning to ask  @jethrokuan about that (consider this ping a weird way to ask about that haha).

**Comment by jethrokuan** [comment]
@ThomasFKJorna done.

**Comment by ThomasFKJorna** [comment]
That was fast! Thank you!
