### ISSUE TITLE
Nodes not showing up after "Expand node"

### ISSUE THREAD

**Issue by emwal** [org-roam/org-roam-ui#14]
First of all thank you for making this!

When poking around I found, that when clicking nodes once to "expand" them and to show only the network around them, they are invisible.
A "hack" around this is turning the 3D view on (and off if you only want to see 2D) – then the nodes show up.

**Comment by emwal** [comment]
Just tried again - and it works, if you don't visit any buffers.
When trying to single out a opened buffer, the nodes don't show up.

**Comment by ThomasFKJorna** [comment]
Huh, could you take some screenshots of this? My guess is that the nodes are there, the zoom function is just kind of janky on not showing them correctly. Could you try zooming out and panning around, and/or calling `(orui-node-local)` from emacs?

**Comment by emwal** [comment]
Indeed, it is the focusing. The nodes do show up, but are not onscreen.
They do show up after zooming out.

**Comment by ThomasFKJorna** [comment]
Hmmm very strange! The zooming feature works a bit unreliably when going from global to local mode and we're working to fix that. One of the problems is that force-graph reeeeaaally wants the clicked node to be at the 0,0 coordinates, so it yoinks them over there by default. Hmm, maybe we should just zoom over there by default now that I think about it, let me try it.

**Comment by ThomasFKJorna** [comment]
This should work a little better now. Instead of trying to fit all the nodes in the viewport, it will just zoom to 0,0 where the nodes are going to be. It won't zoom in on them though, so you should figure out a comfortable level.
