### ISSUE TITLE
Image ratio not respected in preview mode [BUG]

### ISSUE THREAD

**Issue by alexandergogl** [org-roam/org-roam-ui#140]
**Describe the bug**

A wide image with a resolution of 2734 x 1386 px is distorted into a square image (415 x 415 px; ratio 1:1) in node preview. This happens with png and jpeg, and with relative and absolute filepaths alike.

**To Reproduce**

```
#+attr_org: :width 200px
[[file:../../assets/halloween-pumpkins.png]]
```

**Expected behavior**

The image is resized to fit the width of the preview panel and the aspect ratio is kept.

**Screenshots**

Original image

<img width="400" alt="halloween-pumpkins" src="https://user-images.githubusercontent.com/6707564/139702541-39263209-1a8d-4a89-83aa-7b28155ea28c.png">

Image distorted in node preview.

<img width="400" alt="halloween-pumpkins" src="https://user-images.githubusercontent.com/6707564/139702480-a63e561e-6c64-4e61-8679-b0468a39d3eb.png">

**What browser were you using?**

Chrome, Firefox

**Comment by alexandergogl** [comment]
Disabling the css attributes `height: 0px;` and `min-height:100%` in `element.style` will render the image in the correct aspect ratio. But then, the image is vertically centered inside the 400 x 400 px div.

<img width="416" alt="Bildschirmfoto 2021-11-01 um 17 15 03" src="https://user-images.githubusercontent.com/6707564/139705369-4e0342f9-fbff-403a-b8bf-63734a84789f.png">

**Comment by ThomasFKJorna** [comment]
This should be fixed now, I ditched NextJS' image component and now they behave somewhat normally!

**Comment by alexandergogl** [comment]
Now it works as expected. Thanks a lot!
