### ISSUE TITLE
[BUG] Error (websocket): in callback `on-message': Symbol's function definition is void: org-roam-node-find-noselect

### ISSUE THREAD

**Issue by gcoladon** [org-roam/org-roam-ui#149]
**Describe the bug**
When I click the "Open in Emacs" link in the UI, I get the following error message in Emacs:
Error (websocket): in callback `on-message': Symbol's function definition is void: org-roam-node-find-noselect

**To Reproduce**
Which specific things did you do which lead to said bug? E.g. what did you click, which commands did you call, etc.
1. Go to the UI
2. Click on a node to bring it up in the sidebar
3. Click on the three dot hamburger in the upper right
4. Select "Open in Emacs"
5. See error

**Expected behavior**
I thought it would just open up in Emacs.

**Screenshots**
I don't think this would be helpful?

**What browser were you using?**
Brave 

**Additional context**
I'm running Doom Emacs. I just installed org-roam-ui for the first time 10 minutes ago.

**Comment by ThomasFKJorna** [comment]
Hmmm strange, that's a function that should exist on org-roam. Are you running the latest version of org-roam? I.e. have `(unpin! org-roam)` in your `packages.el`?

Could you do `SPC-h-f org-roam-node-find-noselect` and check if the function is there? It is for me, and it should exist in the latest version of `org-roam`,
https://github.com/org-roam/org-roam/blob/3e47f198c7b6c3254944d98357e41840e5e1b102/org-roam-node.el#L411-L423

Other possible cause could be that org-roam is not properly loaded, maybe try an `org-roam-node-find` to get it to load properly>

**Comment by rockt** [comment]
I am running into the same issue. I don't think `org-roam-node-find-noselect` exists in org-roam master anymore.

**Comment by muehlburger** [comment]
> I am running into the same issue. I don't think `org-roam-node-find-noselect` exists in org-roam master anymore.

I run into the same issue. In the [master branch](https://github.com/org-roam/org-roam/blob/master/org-roam-node.el) `org-roam-node-find-noselect` does not exist anymore.

**Comment by muehlburger** [comment]
I can confirm that https://github.com/org-roam/org-roam-ui/pull/214 fixes this issue too.
