### ISSUE TITLE
Missing nodes cause breakage

### ISSUE THREAD

**Issue by jethrokuan** [org-roam/org-roam-ui#15]
If there's a link containing an ID that does not correspond to a node, we see an exception thrown:

```
node not found: uuid
```
 
which is not appropriately handled so the graph stops working.

**Comment by ThomasFKJorna** [comment]
We were indeed only checking for this in the local mode, not the global. Latest push should fix this!

**Comment by ThomasFKJorna** [comment]
Okay I don' think this is fixed yet, I will look into it tomorrow, or maybe @kirillrogovoy  has a better idea.

**Comment by ThomasFKJorna** [comment]
This should be fixed now, maybe we can add a notice that some links are missing in the future. Please reopen if it still does not work!
