### ISSUE TITLE
roam-bibtex/org-ref reference links are not shown

### ISSUE THREAD

**Issue by alxleroux** [org-roam/org-roam-ui#157]
**Describe the bug**

There are no edges between nodes which reference each other using `cite:bibtexkey`. 

The links are correctly identified in the "org-roam-buffer"

**To Reproduce**

Requires org-roam, roam-bibtex, org-ref, org-roam-ui

have a file 

```
:PROPERTIES:
:ID:       1234-5689-...
:ROAM_REFS: cite:bibtexkey1
:END:
#+title: Article 1

This note cite the second one cite:bibtexkey2
```

```
:PROPERTIES:
:ID:       5689-1234-...
:ROAM_REFS: cite:bibtexkey2
:END:
#+title: Article 2

This note cite the first one cite:bibtexkey1 

```

**Expected behavior**
An edge is draw in ORUI between Article 1 and Article 2. 

**Screenshots**
![Screenshot_2021-11-17_16-43-16](https://user-images.githubusercontent.com/55690440/142232746-83105a3e-9160-4200-b295-bb574bb5823e.png)

![Screenshot_2021-11-17_16-43-43](https://user-images.githubusercontent.com/55690440/142232757-096dca3f-8e0b-403c-8d51-5eb33fd22fa7.png)

**What browser were you using?**
Firefox (but same happens with chromium)

**Additional context**
I've just updated from roam v1 to v2.

**Comment by ThomasFKJorna** [comment]
Hmm these work for me
![image](https://user-images.githubusercontent.com/21983833/142239500-0618fd9f-c70f-4af2-848b-ff2b4957e7f9.png)

Which version of org-ref are you using? Might very well be that something changed in the way these things are read by org-roam-bibtex when using v3. I'm still on v2. I don't really know of a quick way to check this.

orui may try to do citation lookup "the old way" which is not really supported anymore. Could you do a `M-x org-roam-version` and a `C-h f org-roam-db-map-citations`? or eval this:
```emacs-lisp
(fboundp #'org-roam-db-map-citations)
```

If it does not exist or that returns `nil` then that is most likely the problem.

**Comment by ThomasFKJorna** [comment]
Whoops, fatfingered that

**Comment by pobermei** [comment]
I have the same problem as OP. My versions are:
```
emacs: 27.2.59
org-roam: v2.1.0-63-gd93423d
org-ref: 3.0
org-roam-ui: git commit 2b167cd
```
Function `org-roam-db-map-citations`  exists.

**Comment by pobermei** [comment]
> I have the same problem as OP. My versions are:
> 
> ```
> emacs: 27.2.59
> org-roam: v2.1.0-63-gd93423d
> org-ref: 3.0
> org-roam-ui: git commit 2b167cd
> ```
> 
> Function `org-roam-db-map-citations` exists.

Whatever has changed since the last 3 days, citation `cite:&key` and ref links are now shown as expected. My current versions are:

```
- Emacs: GNU Emacs 27.2.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30)
 of 2021-11-20
- Framework: 
- Org: Org mode version 9.5 (9.5-g652e8d @ /home/phil/.emacs.d/straight/build/org/)
- Org-roam: v2.1.0-64-ga2e46db
```

**Comment by ThomasFKJorna** [comment]
Yes this seems to have been org-roam specific. Closing this as I presume this is solved, feel free to open it back up again if it keeps being a problem!
