### ISSUE TITLE
[BUG] Headings with statistic cookies don't respect hierarchies

### ISSUE THREAD

**Issue by maikol-solis** [org-roam/org-roam-ui#158]
**Describe the bug**
If a heading has a [statistic cookie,](https://orgmode.org/manual/Breaking-Down-Tasks.html) the hierarchy of the nodes is broken. 

For example, if you have this structure 

```
* A
:PROPERTIES:
:ID:       20211117T094804
:END:
** B
:PROPERTIES:
:ID:       20211117T094846
:END:
*** C
:PROPERTIES:
:ID:       20211117T095027
:END:
```
In the server they show perfectly

![image](https://user-images.githubusercontent.com/4078489/142241853-5e371bba-dc82-411f-abac-262290c4b0b5.png)

Now if you add statistic cookies to the nodes like this

```
* A [0/0]
:PROPERTIES:
:ID:       20211117T094804
:END:
** B [0/0]
:PROPERTIES:
:ID:       20211117T094846
:END:
*** C
:PROPERTIES:
:ID:       20211117T095027
:END:
```
You'll get this layout 

![image](https://user-images.githubusercontent.com/4078489/142242758-2f5d1c02-fb65-4c71-963b-693b316d0a60.png)

**Expected behavior**

The same hierarchy with or without statistic cookies in headlines

**What browser were you using?**
Firefox

**Comment by ThomasFKJorna** [comment]
Fixed in https://github.com/org-roam/org-roam-ui/commit/6c19ce4b762e9c0c7c72fc0105b85aaaad5beafe

**Comment by maikol-solis** [comment]
Thanks Thomas. It works like a charm!

![image](https://user-images.githubusercontent.com/4078489/144712968-3217ddcf-3c9a-4326-8250-fa463bc2f9e6.png)
