### ISSUE TITLE
feature request: Hilight node which is opened in the emacs buffer

### ISSUE THREAD

**Issue by Arahnoid** [org-roam/org-roam-ui#16]
Hi, firs of all thank you for tis awesome package!

Would it be possible to make the node of the file opened in emacs highlighted? Maybe add an outer ring around it with a bright color.

I have a node with 30+ connections and when I open a child node is very hard to figure out which node I have opened in the graph.

**Comment by ThomasFKJorna** [comment]
There is already an option for that! Under "Colors" in "Visuals", there is the "emacsnode" thingy. This sets the color of the node you are currently visiting. If you set this to a rather unique color (such as white) I think that would work. Other highlighting options may or may not come in the future, but the downside of those other methods (such as drawing rings) is that they're quite slow, so we may not implement that. Hope this is good enough for now!

**Comment by Arahnoid** [comment]
Thank you, now I see :) 
So many nice options it is easy to miss it ;)
