### ISSUE TITLE
[ENH] Replace "blacklist"/"whitelist" with "blocklist"/"allowlist"

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [org-roam/org-roam-ui#165]
The filter window in the browser view offers to create a "blacklist" and a "whitelist" with tags.

Would you mind to modify that strings to "blocklist" and "allowlist"?

The primary discussion about things like that are done in other places. I do not want to waste your time with that here. It is just a wish.

**Comment by ThomasFKJorna** [comment]
Thanks for the suggestion, and I would not mind at all! 

The black/whitelists will get removed soon anyway to make way for a more sophisticated querying system, but that is taking longer than I want it to, so I will change the names for the time being, expect that sometime soon!

Thanks for reaching out
