### ISSUE TITLE
Unable to display interface !!

### ISSUE THREAD

**Issue by ISouthRain** [org-roam/org-roam-ui#166]
## Error report 
Error (websocket): in callback `on-message': could not parse JSON stream: "unable to decode byte 0xb9 near 'Ko'", "<string>", 1, 2, 2

**Comment by ThomasFKJorna** [comment]
Did this get resolved? Seem like it could be an encoding issue

**Comment by ISouthRain** [comment]
I don't know what is caused, I didn't modify any configuration, the same system, but now it has been restored!
It has already worked, no error!

**Comment by ThomasFKJorna** [comment]
Those are my favorite kinds of bugs: those who resolve themselves haha

**Comment by ISouthRain** [comment]
I feel so sorry!
My English is not very good.
Are you laughing at me?

**Comment by ThomasFKJorna** [comment]
Oh no not at all! I'm just happy the issue resolved itself :)

**Comment by ISouthRain** [comment]
Oh,good uck!
This project is great!
