### ISSUE TITLE
Biank Screen: Uncaught TypeError: Invalid attempt to spread non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

### ISSUE THREAD

**Issue by 1337m4ks** [org-roam/org-roam-ui#17]
After installing and enabling universal 
The screen is blank
![2021-07-31-164040_563x514_scrot](https://user-images.githubusercontent.com/88255509/127754790-73ce4363-0e4b-4311-bd29-ce88fa4a2901.png)

NextJS 7
        o
        o
        fe
        fe
        _callEventListener
        _handleMessage
        _handleMessage

    NextJS 6
        o
        o
        fe
        fe
        _callEventListener
        _handleMessage
    forEach self-hosted:205
    _handleMessage NextJS

![2021-07-31-155215_901x962_scrot](https://user-images.githubusercontent.com/88255509/127754177-f2d90255-bf32-4e96-b8f7-d96dea9d0e25.png)

**Comment by ThomasFKJorna** [comment]
Huh. Could you provide some more context for when this happens?

**Comment by 1337m4ks** [comment]
Updating now

**Comment by 1337m4ks** [comment]
Added some screenshots / info
If need more info let me know

**Comment by ThomasFKJorna** [comment]
Hmmm very strange, never seen this error before and I thought I saw them all. Are you using org-roam V2 and have all the dependencies installed?

**Comment by 1337m4ks** [comment]
Let me check

**Comment by ThomasFKJorna** [comment]
Since it mentions that something goes wrong after the connection step, it seems that it isn't able to read your graphdata, since that's the only thing that's immediately sends. which suggests that something is wrong with your org-roam config.

**Comment by 1337m4ks** [comment]
I checked depens and they are there 
Ill check my org roam config

**Comment by 1337m4ks** [comment]
It was a simple problem
There were no nodes that had links
I assume that without any links, that the array iteration cannot load (with no links, it is not an array?) 
Its confusing bc the UI menu doesnt load unless array parser(?) also loads
Will modify screenshot to remove hashes and then close

**Comment by ThomasFKJorna** [comment]
Glad to hear this is resolved! What do you mean by 
> also nb: Dont forget default ID for nodes is a hash, not the title
by the way? We do treat the id as a the org ID, or at the very least, whatever org-roam deems to be the id, namely the thing coming after [[id: . If you put something else than a hash there, org-roam(-ui) will just treat that as the id.
