### ISSUE TITLE
[MINOR] org-footnote preview

### ISSUE THREAD

**Issue by zrquan** [org-roam/org-roam-ui#170]
**Have you checked whether this feature is not already on the [project board](https://github.com/org-roam/org-roam-ui/projects/2)?**

No

**Is your feature request related to a problem? Please describe.**

The preview card does not support the org-footnote feature.

**Additional context**
![image](https://user-images.githubusercontent.com/33086594/143513710-5e62eb4d-57db-4029-8e63-d8bb4cd06796.png)

**Comment by rasendubi** [comment]
[uniorg-rehype](https://github.com/rasendubi/uniorg/tree/master/packages/uniorg-rehype) does not support footnotes yet. (Parsing works but uniorg→HTML does not.)

I’ll update this thread when it’s done, though I’m slightly overwhelmed at the moment. If someone wants to implement this faster, I can provide guidance

**Comment by ThomasFKJorna** [comment]
Ah I can give that a shot, let me see

**Comment by ThomasFKJorna** [comment]
I added a pr!

**Comment by rasendubi** [comment]
Footnotes support is released in uniorg-rehype@0.4.8. Opened a PR to update it in org-roam-ui: https://github.com/org-roam/org-roam-ui/pull/172
