### ISSUE TITLE
[ENH] Allow zooming to be disabled

### ISSUE THREAD

**Issue by ngharrison** [org-roam/org-roam-ui#173]
When navigating between nodes within Emacs, org-roam-ui follows by zooming in to that node and its connections. I would like a toggle to disable this so a static view of the graph is maintained and just the highlighting changes. My main reason is that when I switch to a node with no connections, it zooms in so only that node is visible and I lose all possible context of other nodes.

Beautiful package :) I was amazed at the features it offers when I first tried it.

**Comment by ThomasFKJorna** [comment]
There is actually a setting for this already! Check the Behavior tab in the tweaks panel! :)

**Comment by ngharrison** [comment]
Ah thank you very much! Just missed it.
