### ISSUE TITLE
[BUG] [DOC] Manual installation instructions gone from README but still linked in TOC

### ISSUE THREAD

**Issue by thriveth** [org-roam/org-roam-ui#176]
**Describe the bug**
The table of contents in the repo README contains a sub-entry "Manually" under "Installation", but the link points nowhere and there are no instructions for manual installation anymore.

**To Reproduce**
N/A

**Expected behavior**
Either:
a. A section describing the manual installation process (preferred), or 
b. No link or TOC entry to said section.

**Screenshots**
N/A

**What browser were you using?**
Any

**Comment by ThomasFKJorna** [comment]
Good catch, thanks!

**Comment by thriveth** [comment]
The section now is still containing instructions to load "private" to load-path, while the instructions to clone the git repo there are gone. I don't suppose that was the intention?
