### ISSUE TITLE
[BUG] Contents of notes is not shown: "(could not find node)" 

### ISSUE THREAD

**Issue by azhutov** [org-roam/org-roam-ui#177]
**Describe the bug**
When I click on any note in the graph, a sidebar opens with the following message "(could not find node)" inside a note instead of the note's content itself.
At the same time, I could right click on a node, choose "Open in Emacs" and then I could see the contents in emacs.

**To Reproduce**
1. Open emacs
2. Run ```org-roam-ui-open```
3. In the browser, click on any note on a graph
4. Observe "(could not find node)" message on the sidebar instead of contents of a note.

**Expected behavior**
I expect to see the content of the note.

**Screenshots**
![image](https://user-images.githubusercontent.com/68073689/144700582-ddcd56b2-aa0c-4acb-b3de-212094d574c3.png)

**What browser were you using?**
Brave/Firefox

**Additional context**
I use doom emacs. Before performing this test, I run ```doom/upgrade``` to update the packages.
The packages related to org-roam in the packages.el file of doom emacs:
![image](https://user-images.githubusercontent.com/68073689/144700548-4e3056f9-3291-48bd-aeb6-8a0e703d9b90.png)

**Comment by ThomasFKJorna** [comment]
Hmm this probably means that there's something wrong with the way the note is fetched from Emacs. Could you check the Network tab in the developer console for me? (F12)

Should try to make some kind of failing request. Maybe you are using a file name format that does not properly get decoded?

**Comment by azhutov** [comment]
Hello Thomas,
Your hint with the developer console is useful. 

Here are additional tests with information from developer console.

- Case 1: org-roam-ui-port is set to 35900
1. When I double click on a specific node, ORUI sends a request URL to http://localhost:35901/, **but it is supposed to send the request to port 35900**.
![image](https://user-images.githubusercontent.com/68073689/144719055-fc5394aa-3b86-438a-a811-303b544c5cd2.png)

2. When I manually send the same request with the correct port 35900, I could see the content of the note.
3. I could see the graph on http://localhost:35900/, but not on http://localhost:35901/ which make sense due to the point 1.
4.  The information about related ports and processes running:
![image](https://user-images.githubusercontent.com/68073689/144718478-2c5019e1-46d0-4736-8385-faeba29d13a5.png)
- Case 2: org-roam-ui-port is set to 35901
ORUI sends a request URL to http://localhost:35901/ and this is what supposed to happen:
![image](https://user-images.githubusercontent.com/68073689/144718890-017cf844-b874-49ce-9670-4e748ce20cf8.png)
I could now see the text of a node in the sidebar. Here is again the information about related ports and processes running:
![image](https://user-images.githubusercontent.com/68073689/144718921-70d78186-90e1-49a5-bf41-f706ce8d5485.png)

I'm not sure what could be the reason of behavior described in the case 1. I would assign a low priority for investigation of this because it could be easily fixed with assignment of different port. In addition, the problem could be system specific.

Finally, Thank you for the development of this great project. It allows me, and many other people from different fields to better see connections between their notes.

**Comment by ThomasFKJorna** [comment]
Ah I see! We don't support setting the port manually atm (it's a `defvar` rather than a `defcustom`) so I would recommend keeping it at 35901 rather than setting it to something else.

We do want to you to be able to set the port sometime in the future, but atm that's not possible i'm afraid
