### ISSUE TITLE
Links between node missing after zoom-in to a node

### ISSUE THREAD

**Issue by danhuynhdev** [org-roam/org-roam-ui#18]
Zoom in to a node and un-zoom makes all the links disappear.
![Peek 2021-08-01 09-48](https://user-images.githubusercontent.com/17341000/127757498-3ff11bc7-3f10-422f-b6cb-13329cfb88c3.gif)

Note: I use double click outside of node to unzoom. Zooming using Emacs works fine.

**Comment by Jousimies** [comment]
Have same problem here. After expand to a node, link do not display.

**Comment by CUexter** [comment]
Same problem here, Can confirm

**Comment by ThomasFKJorna** [comment]
Hmm yes that should not happen, Pretty sure this is because of the way I tried to fix #15, I'm now filtering links a little *too* aggressively. Apologies! Give me a second

**Comment by ThomasFKJorna** [comment]
This should be fixed now!
