### ISSUE TITLE
Can't see node when it has NOTER_PAGE property

### ISSUE THREAD

**Issue by chuxubank** [org-roam/org-roam-ui#184]
I did some search and find this: https://github.com/org-roam/org-roam-ui/blob/0062fc08917e9ee70148105fe5134e9f4dcf9aba/pages/index.tsx#L872

But can it be customized?
I do have some node have this property and if we don't want to show it, we can use ROAM_EXCLUDE to exclude it any way.

**Comment by chuxubank** [comment]
Never mind...
I find the config in filter.
Maybe we should include it in document?

**Comment by larrasket** [comment]
Yes this was hard to fine.. I think it should be either enabled by default or clear in the document. For anyone else looking, open filters and disable "org noter pages".
