### ISSUE TITLE
[BUG] Nodes don't display `:` Error `on-open': Wrong type argument: listp

### ISSUE THREAD

**Issue by natask** [org-roam/org-roam-ui#186]
**Describe the bug**
Org roam ui doesn't display any nodes. I get warning, ``Error (websocket): in callback `on-open': Wrong type argument: listp, *tagname*``

**To Reproduce**
1. run org-roam-ui-open

**Expected behavior**

I expected nodes to display and not receive the warning. The ui configuration menu displays correctly.

**What browser were you using?**
Firefox/Chrome/Webkit
Firefox 94. it also doesnt work on chrome. 

**Additional context**
I am on branch 05d7de4 for org-roam-ui (latest) and abe63b436035049 for org-roam (latest).

**Debugging**
I debugged and found that error occurs after `websocket-send-text` on when calling `org-roam-ui--send-graphdata` of `org-roam-ui--ws-on-open`. replacing https://github.com/org-roam/org-roam-ui/blob/05d7de409e92dbf3d6b8ef50da0b743c247b4eac/org-roam-ui.el#L440 text, `complete-nodes-db-rows` with `fake-nodes` displays two nodes. 

Replacing https://github.com/org-roam/org-roam-ui/blob/05d7de409e92dbf3d6b8ef50da0b743c247b4eac/org-roam-ui.el#L473 with something else like title allows nodes to display. Therefore something about the structure of properties column isn't currently supported.

**Comment by ThomasFKJorna** [comment]
Hmmm it seems like it indeed has trouble parsing the properties, do you have a node somewhere which has a property called "tagname" or *tagname*?

**Comment by natask** [comment]
the structure of properties is
`((property1 . data1) (property2 . data2) ...)`

the *tagname* that was popping up was actually the data of property1, which was "context" (i.e file name).
I tried only processing cdr. I still get the same problem but now for it reports data of property2 (which are ids) are not lists. This suggests to me either `websocket-send-text` or `json-parse` mistreats cons pairs. I verified this by passing in a cons pair vs list as properties. turns out cons pair throw a similar error, lists work.
  
I wager it is the emacs version I am using (28.5 but haven't updated for months). I will update my emacs and report. I will close this issue until I verify it wasn't my emacs version.
``` elisp
(defun org-roam-ui-sql-to-alist (column-names rows)
  "Convert sql result to alist for json encoding.
ROWS is the sql result, while COLUMN-NAMES is the columns to use."
  (let (res
        (old-rows rows))
    (while rows
      ;; I don't know how to get the tags as a simple list, so we post process it
      (if (not (string= (car column-names) "tags"))
          (if (not (string= (car column-names) "properties"))
              (push (cons (pop column-names) (pop rows)) res)
            (let* ((item (pop rows))
                   (item (cdr item)))
            ;(print item)
            ;(push (cons (pop column-names) `("property" . "data")) res))) ;doesn't work, throws error Error (websocket): in callback `on-open': Wrong type argument: listp, "data"
            ;(push (cons (pop column-names) `("property" "data")) res))) ;works
            (push (cons (pop column-names) item) res))) ;; doesn't work
        (push (cons (pop column-names)
                    (seq-remove
                     (lambda (elt) (string= elt ","))
                     rows))
              res)
        (setq rows nil)))
    res))

```
