### ISSUE TITLE
[BUG] Unable to install on Emacs 27.2

### ISSUE THREAD

**Issue by ddhendriks** [org-roam/org-roam-ui#188]
Hi,

I am trying to install org-roam-ui via MELPA on Emacs 27.2, which I thought would be possible. The MELPA package says that it requires Emacs 27.1, and does not allow me to install org-roam-ui. Is there a way to resolve this, or is the package indeed not available for any version higher than 27.1?

**Comment by ThomasFKJorna** [comment]
Hmm it should work! Do you have a specific error message you could share?

**Comment by ddhendriks** [comment]
I tried to reproduce the message, but I managed  to get it to work before encountering the same issue. I came from a previous installation of Emacs (<27) and perhaps the new installation was just not fully in effect everywhere.
