### ISSUE TITLE
Custom theme not working

### ISSUE THREAD

**Issue by shaunsingh** [org-roam/org-roam-ui#19]
Hello! Sorry for all the issues 

The following snippet of code is what I'm using to theme orui: 
```lisp
#+begin_src elisp
(setq org-roam-ui-custom-theme
      (list
        (bg . '#2E3440')
        (bg-alt . '#3B4252')
        (fg . '#D8DEE9')
        (fg-alt . '#E5E9F0')
        (red . '#BF616A')
        (orange . '#D08770')
        (yellow .'#EBCB8B')
        (green . '#A3BE8C')
        (cyan . '#88C0D0')
        (blue . '#81A1C1')
        (violet . '#B48EAD')
        (magenta . '#8FBCBB')))
#+end_src
```

However, that gives this error: 
```
Error in private config: config.el, (invalid-read-syntax # 1 0)
```
At the 3rd line (in front of bg), any idea what I could be doing wrong?

**Comment by ThomasFKJorna** [comment]
Ah yes. The example provided is not correct, you should use double instead of single quotes here. Single quote indicated a literal in Elisp, so emacs is looking for a symbol called #2e3440, which does not exist.

**Comment by shaunsingh** [comment]
Now it gives the following error: 
`Error in private config: config.el, (wrong-type-argument listp #2E3440)`
With the following code: 
```lisp
#+begin_src elisp
(setq org-roam-ui-custom-theme
      (list
        (bg . "#2E3440")
        (bg-alt . "#3B4252")
        (fg . "#D8DEE9")
        (fg-alt . "#E5E9F0")
        (red . "#BF616A")
        (orange . "#D08770")
        (yellow ."#EBCB8B")
        (green . "#A3BE8C")
        (cyan . "#88C0D0")
        (blue . "#81A1C1")
        (violet . "#B48EAD")
        (magenta . "#8FBCBB")))
#+end_src
```

**Comment by nobiot** [comment]
Might I suggest that you try this?
Instead of the `list` function, use the "`" back-tick notation...
I believe that's what @ThomasFKJorna is going for. At least you can set the variable this way.

```
(setq org-roam-ui-custom-theme
      `((bg . "#2E3440")
        (bg-alt . "#3B4252")
        (fg . "#D8DEE9")
        (fg-alt . "#E5E9F0")
        (red . "#BF616A")
        (orange . "#D08770")
        (yellow ."#EBCB8B")
        (green . "#A3BE8C")
        (cyan . "#88C0D0")
        (blue . "#81A1C1")
        (violet . "#B48EAD")
        (magenta . "#8FBCBB")))
```

**Comment by shaunsingh** [comment]
Thank you, that works perfectly

**Comment by nobiot** [comment]
Hindsight... It should be the normal single quote, I think. A backquote should be fine (and in this context, the result would be identical) but it doesn't need to be. 

A single quote would be the simpler way (and therefore, better). I will need to invite someone more knowledgeable or a better study of the Elisp syntax documentation... Sorry my brain is a bit tired now.

Glad to learn a backquote worked :)

**Comment by ThomasFKJorna** [comment]
Glad to hear that worked! As single quote should do the same in this situation, as the backtick works the same as the single quote but allows you to have "dynamic arguments" (not sure what the right terminology is) by adding a , in front of whatever you would not like to be "quoted"/taken as a literal. 
You could for instance define the list as `((bg . ,(face-background 'default)) which sets the background face to the default face background (this is actually how org-roam-ui gets your theme). Since your list does not include any "dynamic" arguments, it makes no difference.
Don't know why "list" doesn't work though, guess that works different from how I thought.
