### ISSUE TITLE
[BUG] error missing refs.node_id

### ISSUE THREAD

**Issue by RobinBeekhof** [org-roam/org-roam-ui#197]
**Describe the bug**
I just installed org-roam-ui in emacs doom, following the instructions. But when I start ORUI, I get the following error `Error (websocket): in callback 'on-open': EmacSQL had an unhandled condition: "near line 29: no such column: refs.node_id"
` . And my canvas remains empty in the web-ui

**What browser were you using?**
Safari

**Comment by epsilonhalbe** [comment]
I get the same error with firefox (also doom-emacs) on osx

**Comment by epsilonhalbe** [comment]
got it to work, I did *not* follow the (org-roam) install instructions correctly - in my doom config i had to put `+roam2` instead of `+roam` then it did work (had to delete the db and rebuild it.

**Comment by RobinBeekhof** [comment]
Nice! Tanks, this worked for me too!
