### ISSUE TITLE
Snap camera to expanded node.

### ISSUE THREAD

**Issue by klorophatu** [org-roam/org-roam-ui#20]
Expanding the node should move the camera to it.

**Comment by ThomasFKJorna** [comment]
Hmm it should already do this, or are you talking about 3d? That said, it's often not very reliable, but increasing the "Zoom" time under behavior might help.

**Comment by klorophatu** [comment]
If you decide to move the camera using the mouse, the camera will not snap to the nodes anymore.

**Comment by ThomasFKJorna** [comment]
Ah, you would want the camera to stay fixed on the nodes the whole time, or do you mean that moving the mouse interrupts the zooming animation?

**Comment by klorophatu** [comment]
Moving the mouse interrupts the zooming animation. Also, you could have the camera center on the node through some kind of gravity effect, getting the camera incrementally closer to the node if not moved.

**Comment by ThomasFKJorna** [comment]
Pretty sure the behavior atm is consistent with what you wished, if not please reopen this issue!
