### ISSUE TITLE
[BUG] org-roam-node-find-noselect removed from org-roam

### ISSUE THREAD

**Issue by shader** [org-roam/org-roam-ui#212]
**Describe the bug**
When trying to open node in Emacs, "Error (websocket): in callback `on-message': Symbol's function definition is void: org-roam-node-find-noselect" occurs.

**To Reproduce**
Which specific things did you do which lead to said bug? E.g. what did you click, which commands did you call, etc.
1. Select a node
2. Click 'Open in Emacs' from node menu

**Expected behavior**
Should navigate to node in Emacs.

**What browser were you using?**
Firefox

**Additional context**
The org-roam-node-find-noselect function was removed from org-roam yesterday: https://github.com/org-roam/org-roam/commit/eed1df90f571b19cae1581e7f5d938892b00c24d

**Comment by ThomasFKJorna** [comment]
A great catch, thanks!

**Comment by ewag01** [comment]
Hi -I just installed org-roam-ui today and updated org-roam and am having this problem still
