### ISSUE TITLE
Opens lot of browser tabs when Emacs starts [BUG]

### ISSUE THREAD

**Issue by simakovpa** [org-roam/org-roam-ui#213]
**Describe the bug**

**To Reproduce**
Just default setup:
- install package org-roam-ui from melpa
- no config in .emacs file (I use Emacs 27.2)
- open  Emacs
- see this bug: opens lot of browser tabs with ORUI graph

**Expected behavior**
I expect one tab in my browser

**Screenshots**
![ORUI-bug](https://user-images.githubusercontent.com/18704269/152922377-8ae20821-c852-4c4e-885d-d9e255128ad7.jpg)

**What browser were you using?**
Chrome

**Additional context**
I use Windows 10, Emacs 27.2, compile emacs-sqlite.exe with MSYS2 (or use the exe from [github](https://github.com/nobiot/emacsql-sqlite.exe) ) 

I think it opens one browser tab for each opened in Emacs org-file (I use saved desktop for saving my work space).

![ORUI-bug-2](https://user-images.githubusercontent.com/18704269/152922704-d5980610-ec03-46b8-85a1-fd7a3c28c762.jpg)

**Comment by ThomasFKJorna** [comment]
Hmmm that is kind of weird, I guess I don't know how how this saved-desktop works, but I imagine that it starts all the minor modes for every file that was open, thus triggering orui a bunch. I'm not sure how to fix this atm, but you can set `org-roam-ui-open-on-start` to `nil` for the time being to at least mitigate this. Thanks for the report!

**Comment by simakovpa** [comment]
Thank you for answer. It works for my workflow better than I wanted. Now I can to open/close my graph when I need.
