### ISSUE TITLE
[ENH] Support .org.gpg files

### ISSUE THREAD

**Issue by cafkafk** [org-roam/org-roam-ui#229]
**Is your feature request related to a problem? Please describe.**
As seen in https://github.com/org-roam/org-roam-ui/issues/192, org-roam-ui seems to be unable to handle files that are encrypted with the gpg facilities of both org-mode and org-roam.

While the author of that issue  found a way to navigate to a node through their emacs client, my actual usage of org-roam-ui is severly restricted, because I keep (almost) all my files encrypted with gpg, making org-roam-ui essentially a cloud of disconnected dots showing binary data when previewed.
![2022-03-27_17-39](https://user-images.githubusercontent.com/89321978/160289192-dc56b08f-f5b0-48ff-b7f9-118709231189.png)

**Describe the solution you'd like**
I would be grateful for a solution that was able to treat files with the .org.gpg extension the same as normal .org files. I think the case was also made in the linked issue, that gpg encryption is a marked feature of org-roam, and so it seems very reasonable. I assume this is also gonna be relatively easy to implement, although I imagine there might have to be made so careful considerations regarding security.

So concretely, the ability to preview .org.gpg files, and have them treated like .org files in the graph (showing edges that likely are not drawn right now due to the file not being decrypted).

**Comment by cafkafk** [comment]
I had some free time so I wanted to try and have a crack at this, but I can't replicate this anymore. Now .org.gpg files decrypt correctly and link with other nodes from a cold boot...  ¯\_(ツ)_/¯

**Comment by tefkah** [comment]
huh, cool! Glad this resolved on its own!
