### ISSUE TITLE
org-roam-ui-mode crashing when "Expand Node" is changed to "Never"

### ISSUE THREAD

**Issue by dagfog** [org-roam/org-roam-ui#23]
Tested on Firefox 90.0.2  and Chromium 92.0.4515.107. When I expand the "Behavior" menu and switch Expand Node to "Never", the web interface crashes. It switches to a blank white screen that says "Application error: a client-side exception has occurred (developer guidance)."
Nothing is printed on the *httpd* buffer when this happens, and the UI can still be accessed by using an incognito window. It's not storing any cookies and refreshing the browser cache doesn't seem to help. Restarting org-roam-ui-mode and restarting emacs have no effect either. Once I change that setting in a browser, that browser can no longer access the UI unless I use a private browsing feature.
Screenshot of error message + web console output in Chromium:
![image](https://user-images.githubusercontent.com/85924963/127786899-bc68bf6b-4196-4434-a26c-5a476eb21b7e.png)

- The error messages don't show up until I toggle that setting to "Never". 
- It toggles to "Double click" and "Right click" without crashing. 
- Tested the "Open in Emacs" keybinding and got the same behavior. It switches to right and double clicking, but crashes when I set it to "Never"

**Comment by ThomasFKJorna** [comment]
Huh, that's kind of problematic. You can reset this behavior by going to "Application > Storage" in Chromium or "Storage" in Firefox, then to Local Storage and manually deleting the "Behavior" key, I'll see what I can do about the error in the meantime.

**Comment by ThomasFKJorna** [comment]
I get the exact same behavior, wild.

**Comment by ThomasFKJorna** [comment]
Just pushed a fix: I was trying to make an empty string uppercase, which JS does not like to do.

**Comment by dagfog** [comment]
> Huh, that's kind of problematic. You can reset this behavior by going to "Application > Storage" in Chromium or "Storage" in Firefox, then to Local Storage and manually deleting the "Mouse" key, I'll see what I can do about the error in the meantime.

Ah thank you! That worked for me.

**Comment by dagfog** [comment]
> Just pushed a fix: I was trying to make an empty string uppercase, which JS does not like to do.

Thank you very much, it's working as intended now.

**Comment by dagfog** [comment]
This error is back with the recent updates

**Comment by ThomasFKJorna** [comment]
That's very strange, I'm unable to reproduce this this time. What are your other settings like? Are you using some of the new tag/citation features?

**Comment by ThomasFKJorna** [comment]
I just pushed a fix for a similar error (see #33), maybe this also solves yours? Are you using `#+filetags` at all? If not, then that is probably the cause of the error, but this should be fixed now.

**Comment by dagfog** [comment]
So sorry, some unfortunate coincidences lead me to believe that this was the same bug, but it's not. I will close this and do some more leg work on my end.
