### ISSUE TITLE
[BUG] Org attach preview doesn't work with inherited ID

### ISSUE THREAD

**Issue by danhuynhdev** [org-roam/org-roam-ui#246]
**Describe the bug**
When using org-attach with a file-level ID, the preview seems to ignore the id path and simply replace `attachment:` in file link with `file:`

**To Reproduce**
Using this note
```org
:PROPERTIES:
:ID:       93197811-f69e-4624-b98c-853a31d52355
:ROAM_REFS: https://en.wikipedia.org/wiki/System_context_diagram
:END:
#+title: System context diagram


* Definition :ATTACH:
A system context diagram (SCD) in engineering is a diagram that defines the
boundary between the system, or part of a system, and its environment, showing
the entities that interact with it.This diagram is a high level view of a
system. It is similar to a block diagram.

#+ATTR_HTML: :width 550px
[[attachment:_20220629_135349screenshot.png]]
```

**Expected behavior**
Preview shows the image

**Actual behavior**
Doesn't show the image
**Screenshots**
![image](https://user-images.githubusercontent.com/17341000/176376176-b1341ab7-6ede-4d53-8401-94d2d8512719.png)

**Comment by danhuynhdev** [comment]
This seems to be fixed when adding the  `useInheritance: true` to uniorg-attach.

**Comment by danhuynhdev** [comment]
Can you take a look at the PR @ThomasFKJorna ?

**Comment by rasendubi** [comment]
Hey. Could you please share your values for org-attach-use-inheritance and
org-use-property-inheritance, and whether they have been changed from their
defaults?

**Comment by danhuynhdev** [comment]
![image](https://user-images.githubusercontent.com/17341000/176500055-35069d31-f6e0-44b1-8273-17029922534f.png)
![image](https://user-images.githubusercontent.com/17341000/176500272-c76d0b3a-60fa-4d96-95e2-1780d5f45591.png)
I haven't changed anything related to org-attach so pretty sure this is doom-emacs' default

**Comment by danhuynhdev** [comment]
Found the config in doom-emacs 

https://github.com/doomemacs/doomemacs/blob/bea3cc161c0a803dcf574f32ee555dccf565a5ce/modules/lang/org/config.el#L500-L503

**Comment by danhuynhdev** [comment]
Okay so a proper fix should be looking up that value and pass it to org-ui 🤔
