### ISSUE TITLE
[ENH] Persisting drag and drop 

### ISSUE THREAD

**Issue by nazzacode** [org-roam/org-roam-ui#248]
Right now we have the ability to drag a node around an watch the graph morph but it's a bit of a gimmick as it always bounces back... I thinks there's a huge utility in being able drag and drop nodes to stay in place. 
This would allow us to really "play with our ideas"-- move ideas we like closer together, move overlapping labels apart, arrange into rectangle for a screenshot etc. 

I was thinking maybe a toggle option for this behaviour "Persisting drag and drop"

Let me know if you think this is viable. :smile:

**Comment by tefkah** [comment]
Ahhh alright, I didn't really get what you meant. This is already possible by setting the "center" force to 0 under "Physics" > "Advanced"! This way everything should stay in place.

Sorry for the late reply, been a bit overwhelmed
