### ISSUE TITLE
[BUG] Can't Load on Spacemacs

### ISSUE THREAD

**Issue by nicolasshu** [org-roam/org-roam-ui#252]
**Describe the bug**

**To Reproduce**
Which specific things did you do which lead to said bug? E.g. what did you click, which commands did you call, etc.
1. On the `.spacemacs` file, add it to 
```elisp
(defun dotspacemacs/layers ()
  (setq-default
    ...
    dotspacemacs-additional-packages '(
      ...
      ( org-roam :location
        (recipe :fetcher github :repo "org-roam/org-roam" :files (:defaults "extensions/org-roam-dailies.el")) )
      ( simple-httpd )
      ( websocket )
      ( org-roam-ui :location (recipe :fetcher github :repo "org-roam/org-roam-ui" :branch "main" :files ("*.el" )) )
  )
)
``` 
and also add it to 
```elisp
(defun dotspacemacs/user-config ()
      (use-package websocket
    :after org-roam)
  (use-package org-roam-ui
    :after org-roam
    ;;:hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t)
  )

)
```

Then when you open Spacemacs, it returns: 

```
Error (use-package): Cannot load org-roam-ui Disable showing Disable logging
```

However, whenever I go through `M-x package-install RET org-roam-ui RET`, it ends up working as expected

**Expected behavior**
Expected to load `org-roam-ui`

**Comment by wztdream** [comment]
There is no org-roam layer in spacemacs now, just use org layer and enable org-roam and and org-roam-ui support

**Comment by nicolasshu** [comment]
Right. Though by adding the lines above to my config file, it still was not able to run Org-Roam-UI

**Comment by wztdream** [comment]
> Right. Though by adding the lines above to my config file, it still was not able to run Org-Roam-UI

`dotspacemacs-additional-packages '( `<--- did you add `org-roam` and `org-roam-ui` here? It is wrong, they should be in ` dotspacemacs-configuration-layers`

it should be:
```
   dotspacemacs-configuration-layers
   '(
     (org :variables
          org-enable-roam-support t
          org-enable-roam-ui t
          org-enable-roam-protocol t
          )
)
```
It is super simple in spacemacs.
If not, I did not know where is wrong, I use spacemacs too and org-roam and org-roam-ui all works fine.  You need provide more info, maybe turn on `toggle-debug-on-erro` and paste the backtrace here.

**Comment by nicolasshu** [comment]
My bad. I was being stupid. I was originally using an entirely different method of running org-roam on spacemacs.

**Comment by tefkah** [comment]
glad it worked out on its own 😅
