### ISSUE TITLE
[ENH] Reduce the js dependencies

### ISSUE THREAD

**Issue by plattfot** [org-roam/org-roam-ui#263]
Not sure if this classifies as an enhancement, please relabel if it is not.

**Is your feature request related to a problem? Please describe.**

I recently package this up for guix ([57891](https://issues.guix.gnu.org/57891)) to fix #191 for guix users. I did get some feedback about the minified js and the huge number of dependencies. Guix right now does not handle javascript that well, e.g. see [this mailing thread](https://lists.gnu.org/archive/html/help-guix/2022-09/msg00062.html). The feedback from the guix developer was that guix should generate those minified js files to properly bootstrap this package. But given the sheer number of dependencies this has, it might not be possible in the current state of guix. 

After this long-winded explanation, is it possible to minimize the dependencies for Org Roam UI? It would help a lot for properly package this up.

**Describe the solution you'd like**

As I have zero javascript experience, I have no idea how feasible this is. But I do know that reducing dependencies are hard. And I'll understand completely if the answer is no.

Thank you for a great package!

**Comment by tefkah** [comment]
As to the title of this of this issue: no, i can't reduce the dependencies in a significant enough way to matter. Next.js, the framework used to create org-roam-ui, already has [200 dependencies](https://www.npmjs.com/package/next), not counting those dependencies' dependencies. I cannot make the app without Next.js (or at least, I don't want to) so you'll have to look at a different solution im afraid

**Comment by plattfot** [comment]
Yeah, I suspect as much. Docker image will not work with guix, as it wants to have full control of the dependency graph to be able to reproduce the package. And no worries, hopefully guix will be able to handle JS properly in the future.

Thank you for taking the time to answer.

**Comment by plattfot** [comment]
@podiki. Yeah, just meant that Docker wouldn't be feasible to have in the dependency graph for packaging this for Guix's main channel. And yes, I'll probably see if I can contribute this to Nonguix, in the near future.
