### ISSUE TITLE
[MINOR] - Treat dailies as edges in the graph

### ISSUE THREAD

**Issue by esmongeski** [org-roam/org-roam-ui#267]
**Have you checked whether this feature is not already on the [project board](https://github.com/org-roam/org-roam-ui/projects/2)?**

Yes

**Is your feature request related to a problem? Please describe.**
Similar to [this issue](https://github.com/org-roam/org-roam-ui/issues/68).

When looking at my graph, I tend to see a lot of daily nodes, since my main usage of roam is for journaling. My non-daily nodes tend not to reference many other nodes. But my daily nodes do reference many other nodes, as the come up in my notes for a day.

**Describe the solution you'd like**
It would be cool if org-roam-ui had a setting to **consider daily nodes as edges between roam nodes**. So, instead of just having one roam node mention another, any mention of two nodes in a daily node (likely an org header in a daily node) would be considered a link between the two nodes.

**Describe alternatives you've considered**
I could probably change my note taking habits to more intentionally put links between roam nodes when they are agnostic of journaling context. That said, it would be a lot of re-writing to reorganize this.

**Comment by tefkah** [comment]
I think it's a neat idea but I think it's a bit too custom to implement this. Maybe one day this could be a plugin or something, but for now I'm closing this, sorry!
