### ISSUE TITLE
org-roam-ui-sync-theme not working as expected

### ISSUE THREAD

**Issue by prashantnag93** [org-roam/org-roam-ui#32]
`org-roam-ui-sync-theme` not syncing with doom-themes. When I toggle the theme in doom orui creates a new tab in my browser, which freezes my doom emacs, and still, orui theme remains unchanged.

**Comment by ThomasFKJorna** [comment]
Huh, could you provide some more details maybe? You change the theme with `SPC-h-t`, then run `orui-sync-theme`, and then a new tab is opened which crashes your Emacs? Is org-roam-ui running as well?

**Comment by prashantnag93** [comment]
@ThomasFKJorna I used `SPC-h-t` for changing the theme. after recent update of orui I am getting following Error: 
`Application error: a client-side exception has occurred (developer guidance).`

**Comment by ThomasFKJorna** [comment]
I'm sorry, please delete the keys in "Application > Local Storage", should work again then

**Comment by prashantnag93** [comment]
Thank you.
