### ISSUE TITLE
Abbreviation and year of cites/refs not correctly rendered

### ISSUE THREAD

**Issue by p-sin** [org-roam/org-roam-ui#44]
When I add a ```cite:```-link using ```helm-bibtex```, they are rendered with ```%^{author-abbrev} %^{year} title```, where only the title contains the actual text that it should be. I can confirm that the bibtex entry has the abbrev and date correctly set. A screenshot to illustrate this:

![image](https://user-images.githubusercontent.com/16165726/128466568-645435a2-a98f-490e-aca4-d13de6c8e55d.png)

I'm wondering if this is a bug someone else can reproduce, or an error in my configuration?

**Comment by ThomasFKJorna** [comment]
@blester125 
Any idea?

**Comment by ThomasFKJorna** [comment]
You can set 
```emacs-lisp
(setq org-roam-ui-retitle-refs nil)
```
To get rid of this behavior

**Comment by ThomasFKJorna** [comment]
I actually have the same issue, I forgot to reload org-roam-ui after testing the latest PR, will fix

**Comment by ThomasFKJorna** [comment]
This should be fixed in the latest build. Problem is that the default keywords might not be in 'orb-preformat-keywords'. If they are not, we add them. Not very elegant but eh.

**Comment by blester125** [comment]
I think either the default should change, or our patching of `orb-preformat-keywords` should be does as a `let` around the `orb--preexpand-template` call so we don't globally change their settings
