### ISSUE TITLE
The node text size is too big!

### ISSUE THREAD

**Issue by Jousimies** [org-roam/org-roam-ui#46]
![Screenshot_20210806_224402](https://user-images.githubusercontent.com/72933939/128528097-45e250dc-93cf-40a0-b0ca-ae54e7f06a91.png)

How can I set the font size? I tried change "Label Appearance Scale", but it do not work.

**Comment by ThomasFKJorna** [comment]
I agree, that is a bit unwieldy! Glad to see the reference naming works. I will make a slider for this, as well as the text truncation.

**Comment by ThomasFKJorna** [comment]
Latest commit has this configurable!
