### ISSUE TITLE
When no org-ref is introduced it will report an error  org-ref-cite-re

### ISSUE THREAD

**Issue by nailuoGG** [org-roam/org-roam-ui#47]
```
Error (websocket): in callback `on-open': Symbol's value as variable is void: org-ref-cite-re
```

When no org-ref is introduced it will report an error, curious if there is a required function that depends on this package?

**Comment by klorophatu** [comment]
Set `org-roam-ui-retitle-ref-nodes` to `nil`

This is a temporary fix.

**Comment by ThomasFKJorna** [comment]
No it's not required, I think I found the bug, will push a fix in a sec.

**Comment by ThomasFKJorna** [comment]
Latest build should have this fixed, could you test it?

**Comment by nailuoGG** [comment]
Yes it was fixed
