### ISSUE TITLE
Service worker 404

### ISSUE THREAD

**Issue by robbinhan** [org-roam/org-roam-ui#48]
Request this js file

`http://localhost:35901/_next/static/chunks/4.2dee5d830195ddd06029.js`

But no such file in `out` directory but have `4.c9fdfbcb8f8ce1720633.js`

**Comment by ThomasFKJorna** [comment]
I get that error as well, but it does not impede the functioning of the app on my part. It's something with the service worker, which I should remove. I added it when trying to get PWA support, but that wasn't working so now it just complains all the time.

**Comment by robbinhan** [comment]
But it seems to affect me

There is nothing on my browser

![image](https://user-images.githubusercontent.com/241873/128602914-05eb2a39-0acc-4498-a7fa-c66a65791184.png)
![image](https://user-images.githubusercontent.com/241873/128602928-817260e8-255a-4dbe-ae85-b80e5212720b.png)
![image](https://user-images.githubusercontent.com/241873/128602949-bff06606-e209-4c7b-97da-cea2876ac836.png)

**Comment by ThomasFKJorna** [comment]
Huh, there's a lot more wrong than just that yeah. Do you have the latest commit?

**Comment by robbinhan** [comment]
Yes， I use doom, and I did upgrade command. Now org-roam-ui latest commit is on `c745d07018a46b1a20b9f571d999ecf7a092c2e1`

**Comment by robbinhan** [comment]
Oh, I dont know why, but it's ok now

**Comment by ThomasFKJorna** [comment]
Glad it works!

**Comment by robbinhan** [comment]
Thanks, It's still 404, but it works

**Comment by ThomasFKJorna** [comment]
I will leave this open until we fix that.
