### ISSUE TITLE
FEATURE REQUEST: link nodes with its parent node

### ISSUE THREAD

**Issue by aGolduck** [org-roam/org-roam-ui#49]
not just parent files

**Comment by ThomasFKJorna** [comment]
See discussion about this (here)[https://org-roam.discourse.group/t/package-release-org-roam-ui/1871/17].

We'll probably add it at some point, or work with org-roam to implement it there.

**Comment by blester125** [comment]
This PR adds this feature via a large complex 😅 sql query. https://github.com/org-roam/org-roam-ui/pull/53

This query could also be tweaked/parameterized to link each node to the file if we want to move that feature to the backend. I wasn't sure about the design/maintainabliity of the huge sql so I left it as a draft until more people chime in.

Using an org file like below, we can see that the hierarchy is show, and that we don't have false links between nodes and other nodes that share things like titles and outline levels with the actual parent of the node.

```
:properties:
:ID:       53ef05aa-619d-473d-a6a2-35e1bd02c3cf
:end:
#+title: test
#+startup: latexpreview inlineimages

* Headline
:properties:
:ID:       1a2f111a-6b12-469c-b0b4-92a31d977b23
:end:
** Another :bad2:
:properties:
:ID:       a45cbf04-8e71-4c38-9ad4-f2dfa91eeb5b
:end:
** Another
:properties:
:ID:       f11eecf0-bdcb-4124-803b-727e3aa9b70a
:end:
*** Real Note
:properties:
:ID:       667972fd-9711-4993-b38c-c5557607cdd2
:end:

** Second again
*** Real Note 2
:properties:
:ID:       3a7e34c9-0573-4b25-bc1a-10dc813be7a7
:end:
** Another :bad:
:properties:
:ID:       eecf45a0-03e9-4e73-8309-f19ae5d6c7db
:end:
```

**Comment by ThomasFKJorna** [comment]
This is implemented in the latest build.
