### ISSUE TITLE
Follow-mode broken

### ISSUE THREAD

**Issue by thriveth** [org-roam/org-roam-ui#58]
On my system, follow-mode has been broken since commit 10bc61ced096e25c92509d50f598eab53faef834 (i.e., the last commit where it works is e71c0afd6e2bebfc0a9b0273c80bab8cf1ad0181). 

The graph does not show a highlighted Emacs node, and neither does it highlight and follow when navigating nodes in Emacs.

**Comment by ThomasFKJorna** [comment]
I removed a rather crucial space, should work again now.

**Comment by thriveth** [comment]
Brilliant!

**Comment by thriveth** [comment]
I can confirm that it works!
