### ISSUE TITLE
Bug: Tags color sometimes got replaced by adding new coloring pair

### ISSUE THREAD

**Issue by CUexter** [org-roam/org-roam-ui#60]
When I am trying to assign a new tag with a certain color. Sometime it will made existing coloring pair disappeared.

**Comment by ThomasFKJorna** [comment]
Sorry, totally missed this! Could you possibly provide a demonstration of this happening? I can't seem to reproduce it.

**Comment by CUexter** [comment]
Oh no i think it happens because pressing backspace deletd old pairs in tag coloring, is there anyway to turn tha off ?
________________________________
