### ISSUE TITLE
citet:key and citep:key do not show up on graph

### ISSUE THREAD

**Issue by thriveth** [org-roam/org-roam-ui#65]
I have notices that while org-ref style citations like `cite:citekey` are shown well and nice in the graph as either cite- or ref-links (depending on whether there is an existin note on the cited paper or not), the same is not the case when I use `citet:citekey` or `citep:citekey`.

I have tested and org-roam-bibtex does pick up these `citet:` and `citep:` links, as they are showing up in the backlink buffers of papers that have notes, so it must be some subtlety in the database that org-roam-ui doesn't pick up on.

**Comment by ThomasFKJorna** [comment]
Ah, apparently those are added as different kinds of links in the org-roam-db.

This should be fixed in the latest build. I couldn't figure out a clever way to do this so we're just hard coding those in atm, do you know of any other cite commands you can use with org-ref?

**Comment by thriveth** [comment]
There's a very long list at https://raw.githubusercontent.com/jkitchin/org-ref/master/org-ref.org (not visible in the rendered view, unfortunately). But I lost of them are highly specialized, so I suppose a couple up to a handful alternative styles should do it. After all, org-roam is not meant for advanced document preparation. Sendt fra min Galaxy
-------- Oprindelig besked --------Fra: "Thomas F. K. Jorna" ***@***.***> Dato: 16.08.2021  12.36  (GMT+01:00) Til: org-roam/org-roam-ui ***@***.***> Cc: Thøger Rivera-Thorsen ***@***.***>, Author ***@***.***> Emne: Re: [org-roam/org-roam-ui] citet:key and citep:key do not show up on graph (#65) 
Ah, apparently those are added as different kinds of links in the org-roam-db.
This should be fixed in the latest build. I couldn't figure out a clever way to do this so we're just hard coding those in atm, do you know of any other cite commands you can use with org-ref?

**Comment by ThomasFKJorna** [comment]
ah it's just all the natbib/biblatex citation commands. I figured out a cleverer way to do this, so all commands with cite in the name should now be picked up.

**Comment by thriveth** [comment]
Yep, org-ref da mainly geared towards latex users. Can't wait to upgrade to latest version! Sendt fra min Galaxy
-------- Oprindelig besked --------Fra: "Thomas F. K. Jorna" ***@***.***> Dato: 16.08.2021  13.27  (GMT+01:00) Til: org-roam/org-roam-ui ***@***.***> Cc: Thøger Rivera-Thorsen ***@***.***>, Author ***@***.***> Emne: Re: [org-roam/org-roam-ui] citet:key and citep:key do not show up on graph (#65) 
ah it's just all the natbib/biblatex citation commands. I figured out a cleverer way to do this, so all commands with cite in the name should now be picked up.
