### ISSUE TITLE
Children nodes do not correctly link to parent heading nodes.

### ISSUE THREAD

**Issue by blester125** [org-roam/org-roam-ui#67]
When using the test file below, I am seeing some node are linking to nodes in other subtree, for example in the screenshot below we see that the `Read Note 2` which has an olp of `("Headline" "Second Again")` is being linked to the `Another` node with the `:good:` tag when it should be linked directly to the `Headline` node.

It seems there isn't a check for if the parent node is in the child notes olp.

![Screenshot from 2021-08-16 11-37-16](https://user-images.githubusercontent.com/10950530/129590382-baaafedb-8317-49d5-8588-0f89994f6251.png)

Other than that, it seems to correctly handle the edges this file presents. There should probably be a test written based on this file to make sure there aren't regressions in the hierarchical inference.

```
:properties:
:ID:       18434726-762e-42d7-9042-3f71454248b5
:end:
#+title: test
#+startup: latexpreview inlineimages

#+begin_src elisp
(setq org-use-tag-inheritance 'nil)
#+end_src

* Headline
:properties:
:ID:       3d56e3ad-e9f1-405c-b308-306a86cac7b8
:end:
** Another :bad2:
:properties:
:ID:       a4e471b2-3dc3-4061-acde-f73bc7b73773
:end:
** Another :good:
:properties:
:ID:       7605a32c-81f8-45af-9496-702c803c16b1
:end:
*** Another :bad3:
:properties:
:ID:       72d7686f-ceed-47f6-98bb-59d5f5bfb94b
:end:
*** Real Note
:properties:
:ID:       1b242d67-5da1-4159-963b-137df2b03a5d
:end:
** Second Again
*** Read Note 2
:properties:
:ID:       28481dd7-ce04-4d8b-a264-f5933c119bf1
:end:
** Another :bad:
:properties:
:ID:       5004d23d-4c63-4930-9979-1fadd7a8ff65
:end:
```

**Comment by ThomasFKJorna** [comment]
You are correct, it should link to the headline indeed, I'll work on it.

**Comment by ThomasFKJorna** [comment]
Should be fixed now, I even made the test more robust by adding another node with the same title as the actual parent heading above it
```org-mode
:properties:
:ID:       18434726-762e-42d7-9042-3f71454248b5
:end:
#+title: test
#+startup: latexpreview inlineimages

#+begin_src elisp
(setq org-use-tag-inheritance 'nil)
#+end_src

* Headline
:properties:
:ID:       3d56e3ad-e9f1-405c-b308-306a86cac7b8
:end:
** Another :bad2:
:properties:
:ID:       a4e471b2-3dc3-4061-acde-f73bc7b73773
:end:
** Another :good:
:properties:
:ID:       7605a32c-81f8-45af-9496-702c803c16b1
:end:
*** Another :bad3:
:properties:
:ID:       72d7686f-ceed-47f6-98bb-59d5f5bfb94b
:end:
*** Real Note
:properties:
:ID:       1b242d67-5da1-4159-963b-137df2b03a5d
:end:
** Second Again
:PROPERTIES:
:ID:       d4d9912e-5c4e-419b-8eb0-6c64b776eea6
:END:
** Second Again
*** Should link to headline
:properties:
:ID:       28481dd7-ce04-4d8b-a264-f5933c119bf1
:end:
** Another :bad:
:properties:
:ID:       5004d23d-4c63-4930-9979-1fadd7a8ff65
:end:
```

![image](https://user-images.githubusercontent.com/21983833/129602051-ee134e86-d425-4eab-82cf-92fc6cfccdd7.png)


Thanks for pointing this out and guiding me to the OLP property: I'd completely missed it!
