### ISSUE TITLE
Allow excluding dailies from graph

### ISSUE THREAD

**Issue by sopoforic** [org-roam/org-roam-ui#68]
**Have you checked whether this feature is not already on the [project board](https://github.com/org-roam/org-roam-ui/projects/2)?

Yes

**Describe the solution you'd like**
I'd like a toggle to filter dailies out of the graph. Typically, nodes being linked by dailies doesn't represent a meaningful connection, so these links are usually undesirable.

**Describe alternatives you've considered**
I've considered tagging dailies with `daily` and filtering that, but this seems like some unnecessary duplication. It'd be cleaner to determine whether a note is a daily depending on the location of the file (i.e. is the file inside the `org-roam-dailies-directory`?).

**Comment by ThomasFKJorna** [comment]
Ask and you shall receive! Latest commit adds this feature. The filtering is done using the daily directory like you mentioned, not sure if this would work if you daily directory is the same as your normal one.

**Comment by ThomasFKJorna** [comment]
Thank you, glad you like it! :)

**Comment by ThomasFKJorna** [comment]
Ah yes, you're right, should work now regardless of format! Thanks!
