### ISSUE TITLE
[MINOR] Add the option to word-wrap the labels for long titles

### ISSUE THREAD

**Issue by maikol-solis** [org-roam/org-roam-ui#70]
**Have you checked whether this feature is not already on the [project board](https://github.com/org-roam/org-roam-ui/projects/2)?**

yes

**Is your feature request related to a problem? Please describe.**
If there are many nodes together, and the titles are long, the labels become unreadable. 

**Describe the solution you'd like**

Maybe if the user could word-wrap the labels, then the collisions could be less. 

**Describe alternatives you've considered**

Adjusting the fonts or the graph's physics, but any setting that I have tried does not solve the problem. 

**Additional context**
Two examples 

![image](https://user-images.githubusercontent.com/4078489/129776613-3d9b1900-3bf9-446c-b90a-7d4ead881ed3.png)
![image](https://user-images.githubusercontent.com/4078489/129777123-1a03477a-ba6f-4c2e-8f66-d99c2ebd2c29.png)

**Comment by ThomasFKJorna** [comment]
I like this, I've delayed trying to implement it because I did not know whether people wanted/needed it, but I will look into adding it soonish.

**Comment by maikol-solis** [comment]
Thanks. I'll be looking forwarding to.

**Comment by ThomasFKJorna** [comment]
Has been added!

**Comment by maikol-solis** [comment]
Thank you very much.
