### ISSUE TITLE
[MINOR] Show node labels "more intelligently".

### ISSUE THREAD

**Issue by ThomasFKJorna** [org-roam/org-roam-ui#72]
It would be nice to show node labels "more intelligently". Now we can have all labels shown or no labels shown, based on the "label appearance scale". It would be really cool, if it worked something like maps, where you see only the most important labels when zoomed out (big cities) and as you zoom in, more labels (villages, street names, ...) start appearing.
This could be done based on number of in/outcoming links, or perhaps user-specifiable node-importance function.

_Originally posted by @serycjon in https://github.com/org-roam/org-roam-ui/discussions/6#discussioncomment-1201280_

**Comment by iogrt** [comment]
Have you started to work on this? I can try to tackle it.
How should this setting be tweaked?  I thought of changing the label appearance scale to a range (minimum scale for the bigger nodes and max scale for all), using it linearly.
In addition we could also have a granularity setting to control the smoothness of the transition
