### ISSUE TITLE
[BUG] Emacs 26 support: eq: Symbol’s function definition is void: seq-first

### ISSUE THREAD

**Issue by hugovalk** [org-roam/org-roam-ui#75]
**Describe the bug**
Installed org-roam-ui using the manual instructions with fresh source code pulled at time of bug submission. 
When running M-x: org-roam-ui-mode, I get the message:

    eq: Symbol’s function definition is void: seq-first

This is due to the fact that seq-first is introduced since Emacs 27. Since org-roam is supporting Emacs 26 as well, I feel that org-roam-ui should also. 

**To Reproduce**
1. Use an Emacs 26 installation
2. Install the org-roam-ui package using manual instructions (but this should not matter)
3. execute `org-roam-ui-mode`

**Expected behavior**
The org-roam-ui server should start. 

**Additional context**
I supplied the seq-first function in my init.el for now, and that fixes it. 
It seems to be the only Emacs 27/26 compatibility problem (so far).

**Comment by ThomasFKJorna** [comment]
We probably won't support Emacs 26, as the `seq` commands are not the main 27.1 feature: fast JSON parsing is. 

... or so I thought, I'm a bit surprised that that one `seq-first` call is the only problem you encountered. If that's the case I think it'd be a good idea to also support Emacs 26 if it's such a small cost. Thanks for letting me know!

**Comment by hugovalk** [comment]
Hi, thanks for replying, I have had some more time to play with it, and unfortunately I have also encountered the json-parser error  after further testing... 
I've migrated to Emacs 27 for now.

**Comment by ThomasFKJorna** [comment]
Ah that's too bad. Then we probably won't support 26 for the time being (or ever), so I will close this issue.
