### ISSUE TITLE
[BUG] EmacSQL had an unhandled condition: "no such table: citations"

### ISSUE THREAD

**Issue by fosskers** [org-roam/org-roam-ui#78]
**Describe the bug**

After upgrading to the latest commit, I'm no longer able to run `org-roam-ui-mode`.

**To Reproduce**
1. Be on Doom Emacs, configured with:

```lisp
(package! websocket)
(package! org-roam-ui :recipe (:host github :repo "org-roam/org-roam-ui" :files ("*.el" "out")))
```
```lisp
(use-package! org-roam-ui
  :after org-roam
  :config
  (setq org-roam-ui-sync-theme t
        org-roam-ui-follow t
        org-roam-ui-update-on-save t
        org-roam-ui-open-on-start t))
```
2. Run `org-roam-ui-mode`.
3. Browser tab opens, but only shows a gray background.
3. See the error in Emacs.

**Expected behavior**

I expected Org Roam to start.

**What browser were you using?**
Chromium

**Additional context**
Emacs 28

**Comment by vp275** [comment]
I'm on Doom emacs too, and have been getting the same error as @fosskers 
Only difference: I'm on emacs27.2.

**Comment by zyxir** [comment]
I am on vanilla Emacs 27.1 and have been getting the same error too.

**Comment by ThomasFKJorna** [comment]
Hmm I should have probably put in a check for this, my bad! Please upgrade your org-roam to the latest version, if you are using Doom Emacs, put 
```
(unpin! org-roam)
```
in your `packages.el`

**Comment by ThomasFKJorna** [comment]
Reason for this happening is that Doom pins org-roam to a specific commit, I will ask for a bump in the version.

**Comment by ThomasFKJorna** [comment]
This latest commit *should* fix it, but I can't test it as exhaustively as I'd like as org-roam complains about my db being too new, even though I've deleted it. Regardless, it should work, it might just not show you the "non-existant" citations now. I will update the readme to recommend using the latest version.

**Comment by vp275** [comment]
I already had the unpin line in my packages.el and I'm still getting the same error.

**Comment by ThomasFKJorna** [comment]
Could you try running `org-roam-db-sync`? 
If that doesn't seem to do anything, could you show me the output of `(org-roam-version)`?

**Comment by vp275** [comment]
I ran `org-roam-db-sync`. Still getting the same error. 

Running `org-roam-version` returns `2.0.0`

**Comment by ThomasFKJorna** [comment]
Then the unpinning was not successful, either because you are loading something which requires org-roam before the `(unpin!)` or because an upgrade did not go well.

You can either
1. Pull the latest org-roam-ui version, which includes a check for this behavior, or
2. Manually remove the org-roam repo and build and then run doom sync again. This is how I usually force an incremental upgrade (not very elegant, but eh)
``` shell
rm -rf ~/.emacs.d/.local/straight/repos/org-roam
rm -rf ~/.emacs.d/.local/straight/build-27.2/org-roam
rm -rf ~/.emacs.d/.local/straight/repos/org-roam-ui
rm -rf ~/.emacs.d/.local/straight/build-27.2/org-roam-ui
doom sync -U
```
This won't delete your db, just the stored repos.

If after that `(org-roam-version)` still returns `v.2.0.0` instead of either `v.2.1.0` or a string of numbers, something is going wrong in your config.

**Comment by fosskers** [comment]
Thank you for the update. Even without the `unpin`, everything works now that I've upgraded to the latest commit of this repo. Thank you!

**Comment by vp275** [comment]
> Then the unpinning was not successful, either because you are loading something which requires org-roam before the `(unpin!)` or because an upgrade did not go well.
> 
> You can either
> 
> 1. Pull the latest org-roam-ui version, which includes a check for this behavior, or
> 2. Manually remove the org-roam repo and build and then run doom sync again. This is how I usually force an incremental upgrade (not very elegant, but eh)
> 
> ```shell
> rm -rf ~/.emacs.d/.local/straight/repos/org-roam
> rm -rf ~/.emacs.d/.local/straight/build-27.2/org-roam
> rm -rf ~/.emacs.d/.local/straight/repos/org-roam-ui
> rm -rf ~/.emacs.d/.local/straight/build-27.2/org-roam-ui
> doom sync
> ```
> 
> (assuming you are on Linux and have your `.emacs.d` in the default location)
> This won't delete your db, just the stored repos.
> 
> If after that `(org-roam-version)` still returns `v.2.0.0` instead of either `v.2.1.0` or a string of numbers, something is going wrong in your config.

Thanks a lot. I did the second step. It is working now. 

Just one thing. My `org-roam-version` is showing `a8a36a4` now. Have you faced this in the paste?

**Comment by ThomasFKJorna** [comment]
Great to hear things are working now! Yes, it seems like org-roam is now versioning based on commits, which makes sense to me.

**Comment by vp275** [comment]
OH! TIL that is the commit ID. Always thought it was some sort of an error. Thanks a lot for your kind efforts mate. Cheers!
