### ISSUE TITLE
[BUG] Org-roam-ui shows nothing.

### ISSUE THREAD

**Issue by zyxir** [org-roam/org-roam-ui#81]
**Describe the bug**

On the latest commit of org-roam-ui and latest org-roam from MELPA, `org-roam-ui-mode` shows nothing in my browser.

**To Reproduce**

1. On Emacs 27.1 (build 1, x86_64-w64-mingw32) precompiled for Windows.
2. Org-roam is configured with:
```emacs-lisp
(setq org-roam-v2-ack t)
(require-package 'org)
(require-package 'org-roam)
(require 'org-roam)

(unless (executable-find "sqlite3")
  (message "To make org-roam work, you have to install sqlite3"))

(setq org-roam-directory (concat my/zybox-path "org-roam"))
(unless (file-exists-p org-roam-directory)
  (make-directory org-roam-directory))
(org-roam-setup)

(define-prefix-command 'my/org-roam-map)
(general-define-key
 "C-c z" 'my/org-roam-map)

(general-define-key
 :keymaps 'my/org-roam-map
 "c" 'org-roam-capture
 "f" 'org-roam-node-find
 "i" 'org-roam-node-insert
 "t" 'org-roam-buffer-toggle)
```
`require-package` is a function that installs a package from MELPA. By the way, org-roam works completely fine. I recently updated my org-roam from v1 to v2, and have read the guide and successfully converted all my notes. I can access, edit and create notes (nodes) in org-roam without any problem.
3. Org-roam-ui is installed as a submodule for my Emacs config repository, and is updated to the most recent commit. It is configured with:
```emacs-lisp
(require-package 'websocket)
(require-package 'simple-httpd)
(load-library "org-roam-ui")
```
As org-roam-ui is added to my load path in other part of my config, `load-library` runs fine without producing any error.
4. Type `M-x org-roam-ui-mode`.
5. A browser tab named "http://localhost:35901/" opens with nothing but a dark background in it.
6. However, no warnings or errors are observed.

**Expected behavior**

I expected the browser tab to show something about my notes.

**What browser were you using?**

I tried Edge, Firefox and even Internet Explorer, but none of them works.

**Additional context**

1. Currently all my notes are converted from org-roam v1, and I am on a Windows PC with pre-compiled Emacs 27.1.
2. `org-roam-version` returns 2.1.0.
3. All my Emacs config could be found at [my repository](https://github.com/zyxir/dot-emacs), if that is necessary.

**Comment by ThomasFKJorna** [comment]
Hmm, strange. Could you show me the console log of your browser? (press Ctrl+Shift+I)

If this is the first time you have installed org-roam-ui, there shouldn't be any issues with cache and such, so I don't really know what the problem is here.

**Comment by gluax** [comment]
Facing the same issue, here's a screenshot of the console log:

![image](https://user-images.githubusercontent.com/16431709/131814751-3fc5f61d-3204-40e6-a089-0bcfd858c06d.png)

**Comment by ThomasFKJorna** [comment]
Could you expand those errors under NextJS?

**Comment by gluax** [comment]
@ThomasFKJorna, oops, sorry, I can't reproduce the errors anymore since it eventually loaded.

**Comment by zyxir** [comment]
![console-error](https://user-images.githubusercontent.com/39643204/131959286-e3b256a0-19e7-4eed-83ee-03a16a9a7b02.png)

@ThomasFKJorna Sorry for the late reply, this is my console log. It seems similiar to @gluax 's, but my graph never get loaded. Hope this helps.

**Comment by alezost** [comment]
I have the same errors as @gluax had. Here are my "NextJS"s expanded.
![2021-09-03_20:29:35](https://user-images.githubusercontent.com/5346244/132045120-d08fd86b-94b7-4df6-9912-b4df07decb74.png)
![2021-09-03_20:29:54](https://user-images.githubusercontent.com/5346244/132045122-907cb79f-316a-47a2-a808-a98a2e282287.png)

**Comment by ml729** [comment]
I just started using org-roam (only had a few notes) and had the same issue and same errors appear in my console. But after I added my first link between notes, the graph appeared.

**Comment by ThomasFKJorna** [comment]
Apologies for the delay/inconvenience! Thanks for showing the logs and thank you to @ml729 for the hint: this happened because we assumed that people would have links or nodes in their org-roam-db, which of course is not necessarily true if you are just starting out.
It should now work, but I might have missed something, so if it still doesn't work please reopen!

**Comment by Preve92** [comment]
Hi all,
First of all, thanks for the amazing work! Have been using this package for awhile and it really helps visualising my notes.

However, I have encountered the same issue: org-roam-ui doesn't show anything.  When I launch `org-roam-ui-mode` a browser window load the page http://localhost:35901/.  However this is the result:

![image](https://user-images.githubusercontent.com/32065059/135604528-8f8e961e-ccb3-45b7-b22b-26af581897c8.png)

I've tried to wait for the graph to pop up, but after 1 hour nothing showed.  Could you please help me? :pray: 

** My config**

 - Emacs version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.25, cairo version 1.16.0) of 2021-09-23
 - Org version: Org mode version 9.4.6 (9.4.6-g593740 @ /home/marco/.config/emacs/straight/build/org/)
 - org-roam version: v2.1.0-20-g17d8e84
 - Browser: Tried with Chromium Version 93.0.4577.82 (Official Build) snap (64-bit); Vivaldi 4.2.2406.52 (Stable channel) stable (64-bit); and Firefox 92.0 (64-bit). The error in the console is the same for all browser. Cleaned the browsers caches.

Org-roam-ui config

```
;;;;; Org roam UI for visualization of note-links
(use-package websocket
  :after org-roam-ui)

(use-package simple-httpd
  :after org-roam-ui)

(use-package org-roam-ui
  :straight
  (:host github :repo "org-roam/org-roam-ui" :branch "main" :files ("*.el" "out"))
  :after org-roam
  :config
  (setq org-roam-ui-sync-theme t
        org-roam-ui-follow t
        org-roam-ui-update-on-save t
        org-roam-ui-open-on-start t))

```

**Comment by ThomasFKJorna** [comment]
Are you using the latest version of org-roam-ui? Sometimes something goes wrong with the build process and the files don't get included, but the latest version should just work.
