### ISSUE TITLE
[Minor] Open note in new window (For: EXWM | XWidget | EAF)

### ISSUE THREAD

**Issue by greghab** [org-roam/org-roam-ui#82]
**Is your feature request related to a problem? Please describe.**

Related to #52, if you run `org-roam-ui` as either an Xwidget inside Emacs, or if you use [EXWM](https://github.com/ch11ng/exwm) where your web **browser** is always a **frame** managed by Emacs, upon clicking a node on the graph, the web browser gets **replaced** by the note.

  

- Now your graph view is gone :(

  

**Describe the solution you'd like**

As mentioned in #52 by @ThomasFKJorna ,

`The solution would probably be to check whether you are using webkit or exwm, and then open a new window instead of the replacing the current buffer.`

  

- Ideally I would like some way for the clicked note to just always **replace the previous note in the same location** (and maintaining whatever visual frame split I have setup) sort of like the workflow of [Obsidian](https://obsidian.md/), but I'm not sure if that is possible within the constraints of Emacs.

  

**Describe alternatives you've considered**

  

- **Floating a browser in EXWM** (putting it on top of emacs and outside of it's frame management), the note will get sent to various free workspaces. If you do a split on where it puts the note, it picks another free workspace, and shows the note there. Floating doesn't work well.

  

**Additional context**

I believe this affects workflows using: EXWM, Xwidgets, and EAF (Emacs Application Framework). In such scenarios `org-roam-ui` is a frame within Emacs.

**Comment by Hrothgar32** [comment]
For now, you could work around this by opening another Emacs within EXWM, you won't lose the browser window by doing that.
I think I could implement this feature though, I'm going to look at it.

**Comment by ThomasFKJorna** [comment]
> Ideally I would like some way for the clicked note to just always replace the previous note in the same location (and maintaining whatever visual frame split I have setup) sort of like the workflow of Obsidian, but I'm not sure if that is possible within the constraints of Emacs.

This should totally be possible now that i think about it. ORUI just issues an emacs command, so we could just check: "is a window displaying an org-roam note open? In that case, replace it" Not sure what I would expect to happen with multiple windows open, though, any suggestions? Just replace the first?

**Comment by ThomasFKJorna** [comment]
@Hrothgar32  if you want to look into it, it's basically these three lines.
Org-roam-node-visit does seem to accept another argument, but that would only switch to the window displaying the clicked buffer if it exists.
https://github.com/org-roam/org-roam-ui/blob/9ad111d2102c24593f6ac012206bb4b2c9c6c4e1/org-roam-ui.el#L178-L180
