### ISSUE TITLE
[BUG] file-error "Cannot bind server socket" "La dirección ya se está usando" OR "address already in use"

### ISSUE THREAD

**Issue by edumerco** [org-roam/org-roam-ui#86]
Dear orui folx and community. 

I use emacs --daemon on startup (debian 10) and since I installed org-ui yesterday this error appears upon emacs boot: 
**(file-error "Cannot bind server socket" "La dirección ya se está usando")** (address already in use, in English)

If I try to close emacs (trying with the --debug-init) I see that there are 2 process that seems to be active server connections (sorry if my ignorance makes me use incorrect words). 

```
httpd           --      listen  --                        --           Main         (network server on [127 0 0 1 35901])
websocket server on port 35903 <127.0.0.1:37934> --      open    --                        --           Main         (network connection to 127.0.0.1:37934)

```
I can also see that when clicking on a node in the ui graph, emacs doesn't open the clicked node, but spits this message:  

```
Warning (initialization): An error occurred while loading ‘/home/edumerco/.emacs.d/init.el’:

File error: Cannot bind server socket, La dirección ya se está usando

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
Error (websocket): in callback `on-message': Symbol's function definition is void: json-parse-string
Error (websocket): in callback `on-message': Symbol's function definition is void: json-parse-string
Error (websocket): in callback `on-message': Symbol's function definition is void: json-parse-string
Error (websocket): in callback `on-message': Symbol's function definition is void: json-parse-string
Error (websocket): in callback `on-message': Symbol's function definition is void: json-parse-string

```

Commenting in the config... 
`(add-to-list 'load-path "~/.emacs.d/private/org-roam-ui")`
gives a series of not-found issues, but not the cited error. 

My org-mode version is Org mode version 9.4.6 (9.4.6-12-gdcc3a8-elpa @ /home/edumerco/.emacs.d/elpa/org-20210816/)

Can you help me diagnose the origin of this error? 

Also, it may be unrelated but appeared at the same time, the scratch buffer opens in read-only mode. 

Thanks a ton for your time and dedication... :)

.> > > > > > Potentially useful information follows > > > > > >

My related config is

```
            (setq org-roam-v2-ack t)
            (require 'org-roam-protocol)
            
            (setq org-roam-ui-sync-theme t
                      org-roam-ui-follow t
                      org-roam-ui-update-on-save t
                      org-roam-ui-open-on-start nil)

            (add-to-list 'load-path "~/.emacs.d/private/org-roam-ui")
            (load-library "org-roam-ui")
```

and the backtrace (sorry the size) is: 
```
Debugger entered--Lisp error: (file-error "Cannot bind server socket" "La dirección ya se está usando")
  make-network-process(:name "websocket server on port 35903" :server t :family ipv4 :noquery t :filter websocket-server-filter :log websocket-server-accept :filter-multibyte nil :plist (:host local :on-open (closure ((last-message . "Starting new Ispell process /usr/bin/aspell with e...") (arg . 1) t) (ws) (progn (setq oru-ws ws) (org-roam-ui--send-graphdata) (if org-roam-ui-update-on-save (progn (add-hook 'after-save-hook #'org-roam-ui--on-save))) (message "Connection established with org-roam-ui") (if org-roam-ui-follow (progn (org-roam-ui-follow-mode 1))))) :on-message (closure ((last-message . "Starting new Ispell process /usr/bin/aspell with e...") (arg . 1) t) (_websocket frame) (let* ((msg (json-parse-string (websocket-frame-text frame) :object-type 'alist)) (command (alist-get 'command msg)) (data (alist-get 'data msg))) (cond ((string= command "open") (org-roam-node-visit (org-roam-populate ...))) ((string= command "delete") (progn (message "Deleted %s" ...) (delete-file ...) (org-roam-db-sync) (org-roam-ui--send-graphdata))) ((string= command "create") (progn (if ... ...) (org-roam-capture- :node ... :props ...))) (t (message "Something went wrong when receiving a message from..."))))) :on-close (closure ((last-message . "Starting new Ispell process /usr/bin/aspell with e...") (arg . 1) t) (_websocket) (remove-hook 'after-save-hook #'org-roam-ui--on-save) (org-roam-ui-follow-mode -1) (message "Connection with org-roam-ui closed."))) :host local :service 35903)
  websocket-server(35903 :host local :on-open (closure ((last-message . "Starting new Ispell process /usr/bin/aspell with e...") (arg . 1) t) (ws) (progn (setq oru-ws ws) (org-roam-ui--send-graphdata) (if org-roam-ui-update-on-save (progn (add-hook 'after-save-hook #'org-roam-ui--on-save))) (message "Connection established with org-roam-ui") (if org-roam-ui-follow (progn (org-roam-ui-follow-mode 1))))) :on-message (closure ((last-message . "Starting new Ispell process /usr/bin/aspell with e...") (arg . 1) t) (_websocket frame) (let* ((msg (json-parse-string (websocket-frame-text frame) :object-type 'alist)) (command (alist-get 'command msg)) (data (alist-get 'data msg))) (cond ((string= command "open") (org-roam-node-visit (org-roam-populate (org-roam-node-create :id ...)))) ((string= command "delete") (progn (message "Deleted %s" (alist-get ... data)) (delete-file (alist-get ... data)) (org-roam-db-sync) (org-roam-ui--send-graphdata))) ((string= command "create") (progn (if (and ... ...) (orb-edit-note ...)) (org-roam-capture- :node (org-roam-node-create :title ...) :props '...))) (t (message "Something went wrong when receiving a message from..."))))) :on-close (closure ((last-message . "Starting new Ispell process /usr/bin/aspell with e...") (arg . 1) t) (_websocket) (remove-hook 'after-save-hook #'org-roam-ui--on-save) (org-roam-ui-follow-mode -1) (message "Connection with org-roam-ui closed.")))
  (setq org-roam-ui-ws (websocket-server 35903 :host 'local :on-open #'(lambda (ws) (progn (setq oru-ws ws) (org-roam-ui--send-graphdata) (if org-roam-ui-update-on-save (progn (add-hook ... ...))) (message "Connection established with org-roam-ui") (if org-roam-ui-follow (progn (org-roam-ui-follow-mode 1))))) :on-message #'(lambda (_websocket frame) (let* ((msg (json-parse-string ... :object-type ...)) (command (alist-get ... msg)) (data (alist-get ... msg))) (cond ((string= command "open") (org-roam-node-visit ...)) ((string= command "delete") (progn ... ... ... ...)) ((string= command "create") (progn ... ...)) (t (message "Something went wrong when receiving a message from..."))))) :on-close #'(lambda (_websocket) (remove-hook 'after-save-hook #'org-roam-ui--on-save) (org-roam-ui-follow-mode -1) (message "Connection with org-roam-ui closed."))))
  (cond (org-roam-ui-mode (set (make-local-variable 'httpd-port) org-roam-ui-port) (setq httpd-root org-roam-ui/app-build-dir) (httpd-start) (setq org-roam-ui-ws (websocket-server 35903 :host 'local :on-open #'(lambda (ws) (progn (setq oru-ws ws) (org-roam-ui--send-graphdata) (if org-roam-ui-update-on-save ...) (message "Connection established with org-roam-ui") (if org-roam-ui-follow ...))) :on-message #'(lambda (_websocket frame) (let* (... ... ...) (cond ... ... ... ...))) :on-close #'(lambda (_websocket) (remove-hook 'after-save-hook #'org-roam-ui--on-save) (org-roam-ui-follow-mode -1) (message "Connection with org-roam-ui closed.")))) (if org-roam-ui-open-on-start (progn (orui-open)))) (t (progn (websocket-server-close org-roam-ui-ws) (httpd-stop) (remove-hook 'after-save-hook #'org-roam-ui--on-save) (org-roam-ui-follow-mode -1))))
  (let ((last-message (current-message))) (progn (set-default 'org-roam-ui-mode (if (eq arg 'toggle) (not (default-value 'org-roam-ui-mode)) (> (prefix-numeric-value arg) 0)))) (if (fboundp #'org-roam-version) (if (eq (seq-first (org-roam-version)) 49) (progn (message "You are running org-roam %s. Org-roam-ui is only c..." (org-roam-version)) (setq org-roam-ui-mode -1))) (message "Org-roam is either not installed or not running. P...") (setq org-roam-ui-mode -1)) (cond (org-roam-ui-mode (set (make-local-variable 'httpd-port) org-roam-ui-port) (setq httpd-root org-roam-ui/app-build-dir) (httpd-start) (setq org-roam-ui-ws (websocket-server 35903 :host 'local :on-open #'(lambda (ws) (progn ... ... ... ... ...)) :on-message #'(lambda (_websocket frame) (let* ... ...)) :on-close #'(lambda (_websocket) (remove-hook ... ...) (org-roam-ui-follow-mode -1) (message "Connection with org-roam-ui closed.")))) (if org-roam-ui-open-on-start (progn (orui-open)))) (t (progn (websocket-server-close org-roam-ui-ws) (httpd-stop) (remove-hook 'after-save-hook #'org-roam-ui--on-save) (org-roam-ui-follow-mode -1)))) (run-hooks 'org-roam-ui-mode-hook (if (default-value 'org-roam-ui-mode) 'org-roam-ui-mode-on-hook 'org-roam-ui-mode-off-hook)) (if (called-interactively-p 'any) (progn (customize-mark-as-set 'org-roam-ui-mode) (if (and (current-message) (not (equal last-message (current-message)))) nil (let ((local "")) (message "Org-Roam-Ui mode %sabled%s" (if (default-value ...) "en" "dis") local))))))
  org-roam-ui-mode(1)
  desktop-create-buffer(208 "/home/edumerco/Nextcloud/notas/index.org" "index.org" org-mode (abbrev-mode visual-line-mode org-table-header-line-mode override-global-mode beacon-mode smartparens-mode hi-lock-mode helm-mode wrap-region-mode org-roam-ui-mode org-indent-mode flyspell-mode) 730 (730 nil) nil nil ((indent-tabs-mode) (buffer-display-time 24890 29256 398562 791000) (buffer-file-coding-system . utf-8-unix) (truncate-lines)) ((mark-ring (691 29224))))
  eval-buffer(#<buffer  *load*-759105> nil "/home/edumerco/.emacs.d/.emacs.desktop" nil t)  ; Reading at buffer position 12964
  load-with-code-conversion("/home/edumerco/.emacs.d/.emacs.desktop" "/home/edumerco/.emacs.d/.emacs.desktop" t t)
  load("/home/edumerco/.emacs.d/.emacs.desktop" t t t)
  desktop-read()
  eval-buffer(#<buffer  *load*-189981> nil "/home/edumerco/Nextcloud/emacs-init.el" nil t)  ; Reading at buffer position 99819
  load-with-code-conversion("/home/edumerco/Nextcloud/emacs-init.el" "/home/edumerco/Nextcloud/emacs-init.el" nil nil)
  load("/home/edumerco/Nextcloud/emacs-init.el" nil nil t)
  load-file("/home/edumerco/Nextcloud/emacs-init.el")
  org-babel-load-file("/home/edumerco/Nextcloud/emacs-init.org")
  eval-buffer(#<buffer  *load*> nil "/home/edumerco/.emacs.d/init.el" nil t)  ; Reading at buffer position 406
  load-with-code-conversion("/home/edumerco/.emacs.d/init.el" "/home/edumerco/.emacs.d/init.el" t t)
  load("/home/edumerco/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x15656cb1af95>) #f(compiled-function () #<bytecode 0x15656cb1afa9>) t)
  command-line()
  normal-top-level()

```

**Comment by ThomasFKJorna** [comment]
`Error (websocket): in callback `on-message': Symbol's function definition is void: json-parse-string`

This indicates that you aren't using Emacs 27.1 compiled with fast JSON parsing, which is the first thing you should probably fixed. While it is not technically necessary to use orui (we could rely on an old JSON libary), we probably want to do a lot more complex things with ORUI where such speed would be necessary, so we decided to keep it as a requirement.

As for the "Cannot bind to server socket": this usually usually happens to me if I enable org-roam-ui with some faulty configuration, which causes it to not close the websocket when exiting `org-roam-ui-mode`. You can manually close the websocket by deleting the process and then try again. 
I'm not sure what would cause the incorrect initialization here though, are you calling `org-roam-ui` multiple times in your config or something?

**Comment by edumerco** [comment]
Hello @ThomasFKJorna . 

Ok, so there are 2 issues here: 
- one is to recompile emacs with fast JSON parsing. 
- The other issue is the "Cannot bind to server socket". 

### Recompile with json parsing
I understand this is not required but desirable, so I will happily do it. :)

Right now I have here: 
`GNU Emacs 27.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2020-09-03`

I downloaded the source with `git clone https://git.savannah.gnu.org/git/emacs.git` and it's 28.0.50. 
Can I assume it is ok to compile it with 
```
./autogen.sh
./configure --with-native-compilation --with-mailutils
make
make install
```
(I assume I can add more --with-something, right? (after some search, I am starting from https://www.masteringemacs.org/article/speed-up-emacs-libjansson-native-elisp-compilation). 

The previous time I did it with --with-xwidgets --with-cairo --with-rsvg --with-xft so this time would be 
'./configure --with-native-compilation --with-mailutils --with-xwidgets --with-cairo --with-rsvg --with-xft'

Sorry I ask these simple things but I'm no programmer at all so these procedures still makes me a bit (well, quite much really) afraid to break my working environment. :)

### "Cannot bind to server socket"

I found an httpd-stop but upon restarting emacs it happens the same. Upon exiting, emacs says: 
```
Active processes exists; kill them and exit anyway? (y/n)
httpd           --      listen  --                        --           Main         (network server on [127 0 0 1 35901])
```

The backtrace says
```
Debugger entered--Lisp error: (file-error "Cannot bind server socket" "La dirección ya se está usando")
  make-network-process(:name "websocket server on port 35903" :server t :family ipv4 :noquery t :filter websocket-server-filter :log websocket-server-accept :filter-multibyte nil :plist (:host local :on-open (closure ((last-message . "Starting new Ispell process /usr/bin/aspell with e...") (arg . 1) t) (ws) (progn (setq oru-ws ws) (org-roam-ui--send-graphdata) (if org-roam-ui-update-on-save (progn (add-hook 'after-save-hook #'org-roam-ui--on-save))) (message "Connection established with org-roam-ui") (if org-roam-ui-follow (progn (org-roam-ui-follow-mode 1))))) :on-message (closure ((last-message . "Starting new Ispell process /usr/bin/aspell with e...") (arg . 1) t) (_websocket frame) (let* ((msg (json-parse-string (websocket-frame-text frame) :object-type 'alist)) (command (alist-get 'command msg)) (data (alist-get 'data msg))) (cond ((string= command "open") (org-roam-node-visit (org-roam-populate ...))) ((string= command "delete") (progn (message "Deleted %s" ...) (delete-file ...) (org-roam-db-sync) (org-roam-ui--send-graphdata))) ((string= command "create") (progn (if ... ...) (org-roam-capture- :node ... :props ...))) (t (message "Something went wrong when receiving a message from..."))))) :on-close (closure ((last-message . "Starting new Ispell process /usr/bin/aspell with e...") (arg . 1) t) (_websocket) (remove-hook 'after-save-hook #'org-roam-ui--on-save) (org-roam-ui-follow-mode -1) (message "Connection with org-roam-ui closed."))) :host local :service 35903)
  websocket-server(35903 :host local :on-open (closure ((last-message . "Starting new Ispell process /usr/bin/aspell with e...") (arg . 1) t) (ws) (progn (setq oru-ws ws) (org-roam-ui--send-graphdata) (if org-roam-ui-update-on-save (progn (add-hook 'after-save-hook #'org-roam-ui--on-save))) (message "Connection established with org-roam-ui") (if org-roam-ui-follow (progn (org-roam-ui-follow-mode 1))))) :on-message (closure ((last-message . "Starting new Ispell process /usr/bin/aspell with e...") (arg . 1) t) (_websocket frame) (let* ((msg (json-parse-string (websocket-frame-text frame) :object-type 'alist)) (command (alist-get 'command msg)) (data (alist-get 'data msg))) (cond ((string= command "open") (org-roam-node-visit (org-roam-populate (org-roam-node-create :id ...)))) ((string= command "delete") (progn (message "Deleted %s" (alist-get ... data)) (delete-file (alist-get ... data)) (org-roam-db-sync) (org-roam-ui--send-graphdata))) ((string= command "create") (progn (if (and ... ...) (orb-edit-note ...)) (org-roam-capture- :node (org-roam-node-create :title ...) :props '...))) (t (message "Something went wrong when receiving a message from..."))))) :on-close (closure ((last-message . "Starting new Ispell process /usr/bin/aspell with e...") (arg . 1) t) (_websocket) (remove-hook 'after-save-hook #'org-roam-ui--on-save) (org-roam-ui-follow-mode -1) (message "Connection with org-roam-ui closed.")))
  (setq org-roam-ui-ws (websocket-server 35903 :host 'local :on-open #'(lambda (ws) (progn (setq oru-ws ws) (org-roam-ui--send-graphdata) (if org-roam-ui-update-on-save (progn (add-hook ... ...))) (message "Connection established with org-roam-ui") (if org-roam-ui-follow (progn (org-roam-ui-follow-mode 1))))) :on-message #'(lambda (_websocket frame) (let* ((msg (json-parse-string ... :object-type ...)) (command (alist-get ... msg)) (data (alist-get ... msg))) (cond ((string= command "open") (org-roam-node-visit ...)) ((string= command "delete") (progn ... ... ... ...)) ((string= command "create") (progn ... ...)) (t (message "Something went wrong when receiving a message from..."))))) :on-close #'(lambda (_websocket) (remove-hook 'after-save-hook #'org-roam-ui--on-save) (org-roam-ui-follow-mode -1) (message "Connection with org-roam-ui closed."))))
  (cond (org-roam-ui-mode (set (make-local-variable 'httpd-port) org-roam-ui-port) (setq httpd-root org-roam-ui/app-build-dir) (httpd-start) (setq org-roam-ui-ws (websocket-server 35903 :host 'local :on-open #'(lambda (ws) (progn (setq oru-ws ws) (org-roam-ui--send-graphdata) (if org-roam-ui-update-on-save ...) (message "Connection established with org-roam-ui") (if org-roam-ui-follow ...))) :on-message #'(lambda (_websocket frame) (let* (... ... ...) (cond ... ... ... ...))) :on-close #'(lambda (_websocket) (remove-hook 'after-save-hook #'org-roam-ui--on-save) (org-roam-ui-follow-mode -1) (message "Connection with org-roam-ui closed.")))) (if org-roam-ui-open-on-start (progn (orui-open)))) (t (progn (websocket-server-close org-roam-ui-ws) (httpd-stop) (remove-hook 'after-save-hook #'org-roam-ui--on-save) (org-roam-ui-follow-mode -1))))
  (let ((last-message (current-message))) (progn (set-default 'org-roam-ui-mode (if (eq arg 'toggle) (not (default-value 'org-roam-ui-mode)) (> (prefix-numeric-value arg) 0)))) (if (fboundp #'org-roam-version) (if (eq (seq-first (org-roam-version)) 49) (progn (message "You are running org-roam %s. Org-roam-ui is only c..." (org-roam-version)) (setq org-roam-ui-mode -1))) (message "Org-roam is either not installed or not running. P...") (setq org-roam-ui-mode -1)) (cond (org-roam-ui-mode (set (make-local-variable 'httpd-port) org-roam-ui-port) (setq httpd-root org-roam-ui/app-build-dir) (httpd-start) (setq org-roam-ui-ws (websocket-server 35903 :host 'local :on-open #'(lambda (ws) (progn ... ... ... ... ...)) :on-message #'(lambda (_websocket frame) (let* ... ...)) :on-close #'(lambda (_websocket) (remove-hook ... ...) (org-roam-ui-follow-mode -1) (message "Connection with org-roam-ui closed.")))) (if org-roam-ui-open-on-start (progn (orui-open)))) (t (progn (websocket-server-close org-roam-ui-ws) (httpd-stop) (remove-hook 'after-save-hook #'org-roam-ui--on-save) (org-roam-ui-follow-mode -1)))) (run-hooks 'org-roam-ui-mode-hook (if (default-value 'org-roam-ui-mode) 'org-roam-ui-mode-on-hook 'org-roam-ui-mode-off-hook)) (if (called-interactively-p 'any) (progn (customize-mark-as-set 'org-roam-ui-mode) (if (and (current-message) (not (equal last-message (current-message)))) nil (let ((local "")) (message "Org-Roam-Ui mode %sabled%s" (if (default-value ...) "en" "dis") local))))))
  org-roam-ui-mode(1)
  [some-local-loading-files without noticeable errores]
```

If before exiting I execute 'org-roam-ui-mode' it leaves me alone (snifff!) but the `Active processes exists; kill them and exit anyway? (y/n)` doesn't appear, it exits straight away. 

So what do I try? Can I give you more information? 

Thanks a lot... :)

**Comment by ThomasFKJorna** [comment]
This was surprisingly hard to find (I've never compiled Emacs myself), but the flag is simply `--with-json`!

The other issue is somewhat strange, I'm assuming you have `websocket.el` and `simple-httpd` installed? The only thing I can think of is that somehow some other process is using the 35903 port? This port isn't configurable for now, but since all these things happen at startup, could you try not launching ORUI at startup and only launch `org-roam-ui-mode` once your whole Emacs has loaded?
I'm not sure what the best way to do this on vanilla, but I assume something like 
```emacs-lisp
(with-eval-after-load 'org-roam (load-library "org-roam-ui")) 
```
and then do `M-x org-roam-ui-mode` once you are in an org-roam-buffer. 
If you still get that issue (and orui doesnt load at startup) then something else is probably using that port.

The only other info I can think of is showing the output of `M-x list-processes`, but that probably won't be very interesting as the websocket isn't initialized, so it'll just show the httpd server and the org-roam sqlite process,

**Comment by ThomasFKJorna** [comment]
I just reread your original message and saw that you are running Emacs as a daemon... That is probably the reason.

I have two guesses:
1. You are loading org-roam-ui on startup, so the daemon starts up with orui. Then later when (I'm guessing) you're opening a frame, you (manually?) start orui again, which leads to the above error.
2. You are starting the daemon but then start a different process (by for instance calling `emacs --debug-init`, this open another Emacs instance, does not use the daemon) which also tries to initialize an httpd-server and websocket on the same ports, and fails to do so because the daemon Emacs already has instantiated connections there.

For both cases, I think the easiest solution is to not run org-roam-ui-mode on startup but just when you need it to. If you want to run it on startup, don't initialize a separate Emacs process.

The daemon also always causes me a lot of headaches in many ways, but I'm sure it has a solution in the end.

Final thing: to test if ORUI is running somewhere already, just go to `localhost:35901`. If you see something (ideally a graph) then ORUI is already running (probably on the daemon)

**Comment by edumerco** [comment]
Hi Thomas.

> [...] you are running Emacs as a daemon... That is probably the reason.
> I have two guesses:
>    You are loading org-roam-ui on startup, so the daemon starts up with orui. Then later when (I'm guessing) you're opening a frame, you (manually?) start orui again, which leads to the above error.

I am running emacs as daemon and orui on startup. I don't open it again. 

>    You are starting the daemon but then start a different process [...]

Not that I know of...

> [...] The daemon also always causes me a lot of headaches in many ways, but I'm sure it has a solution in the end.

Sure, and it's so useful that I'd prefer to make it run with it... :)

> Final thing: to test if ORUI is running somewhere already, just go to localhost:35901. If you see something (ideally a graph) then ORUI is already running (probably on the daemon)

Yes, it is running on startup. I know it because when I open '''emacs --daemon''' from the command line, the booting messages ends with:

```
Warning (initialization): An error occurred while loading ‘/home/edumerco/.emacs.d/init.el’:
File error: Cannot bind server socket, La dirección ya se está usando
``
So it is part of the initialization process.
Also, upon booting emacs I can open the graph in the browser and it works. 

The only orui thing I have in my init is the one I quoted before:

```
              (setq org-roam-ui-sync-theme t
                        org-roam-ui-follow t
                        org-roam-ui-update-on-save t
                        org-roam-ui-open-on-start nil)
  
              (add-to-list 'load-path "~/.emacs.d/private/org-roam-ui")
              (load-library "org-roam-ui")

```
If the last line in commented, the errors goes away. 

So, how could be load orui but not run it until emacs is loaded? 
Al before, thank you very much for sharing your effort and time with all of us. :)

**Comment by edumerco** [comment]
Hello.

> This was surprisingly hard to find (I've never compiled Emacs myself), but the flag is simply --with-json!

Ah, ok, so I will go for that then, thanks. :)

> The other issue is somewhat strange, I'm assuming you have websocket.el and simple-httpd installed?

Yes, the version that came with my emacs.

websocket:
- Version: 20210110.17
- Commit: fda4455333309545c0787a79d73c19ddbeb57980

simple-httpd:
- Version: 20191103.1446
- Commit: 22ce66ea43e0eadb9ec1d691a35d9695fc29cee6

> The only thing I can think of is that somehow some other process is using the 35903 port? This port isn't configurable for now, but since all these things happen at startup, could you try not launching ORUI at startup and only launch org-roam-ui-mode once your whole Emacs has loaded?
> I'm not sure what the best way to do this on vanilla, but I assume something like
> (with-eval-after-load 'org-roam (load-library "org-roam-ui")) 

I commented the load line and replaced it with yours like this: 
```
;;              (load-library "org-roam-ui")
              (with-eval-after-load 'org-roam (load-library "org-roam-ui"))
```

The result is the same as before. In the command line and in the rest of the behavior. 
Maybe I'm doing something wrong in the way I put it?

> and then do M-x org-roam-ui-mode once you are in an org-roam-buffer. If you still get that issue (and orui doesnt load at startup) then something else is probably using that port.

It seems that orui was already loaded since calling it makes it leave me alone... ;P

> The only other info I can think of is showing the output of M-x list-processes, but that probably won't be very interesting as the websocket isn't initialized, so it'll just show the httpd server and the org-roam sqlite process,

list-processes says: 
```
httpd           --      listen  --                        --           Main         (network server on [127 0 0 1 35901])
ispell          7009    run     --                        --           Main         /usr/bin/aspell -a -m -d es --encoding=utf-8
server          --      listen  --                        --           Main         (network server on /run/user/1000/emacs/server)
server <1>      --      open    --                        --           Main         (network connection to t:/run/user/1000/emacs/server)
websocket server on port 35903 --      listen  --                        --           Main         (network server on local:35903)

```

Is it some more info that could be useful for diagnostic? 

Also, if a synchronous chat or talk is more effective and/or efficient, I don't care about the hour, I'll happily do it at whatever time is good for you. I'm on UTC -0300. :)

Thanks...

**Comment by ThomasFKJorna** [comment]
Both the httpd and websocket server are running so orui should just work, regardless of the errors (which are admittedly annoying).

The main problem seems to be that orui starts up immediately, do you have a hook in place somewhere that calls orui? Like
```emacs-lisp
(add-hook 'after-init-hook #'org-roam-ui-mode)
```
Probably my change didn't do anything since org-roam is loads on startup as well, which makes sense as that is what Jethro recommends you do.

I'm very bad with default Emacs configuration as I'm spoiled by Doom, but I know @nobiot knows things about that. Do you have any idea?

**Comment by edumerco** [comment]
Hi Thomas, I have great news! :)))

While working on this issue I upgraded emacs to 
`GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2021-09-15`
using the options talked before:
`./configure --with-native-compilation --with-mailutils --with-xwidgets --with-cairo --with-rsvg --with-xft --with-json` 

And now everything works perfectly! :smile: 
There was a small error in another block (and unbalanced parenthesis setting up some package), but nothing to do with ouri, at least directly. Strangely, emacs 27.1 didn't talked about it, but 20.5 spit it before anything else. 
I have no idea if that caused the issue, but after fixing it, now it works. 

So we can close this issue with some new knowledge. 
- orui and emacs-daemon have no negative interactions between them.  
- the interaction issues between orui and emacs (ie, not being able to open a file clicking on the graph) were related to this miscommunication since now they're gone. 
- this new emacs version runs visibly faster; in 27.1 loading org-roam v1 was a few seconds, v2 less than a sec, and now in 28.1 it's instantaneous. 
- Compiling with json works ok (even if I see no obvious difference right now, as you said, there may be in the future). 

I'd like to thank you both again for sharing your knowledge, time and dedication, and I hope to be able to give back with my UX experience. :)

Let's keep the talk about the search #85 and whatever good things we can work on this matters. :)
Warmest regards...
