### ISSUE TITLE
[BUG] Nodes in local graph do not expand when clicked

### ISSUE THREAD

**Issue by thriveth** [org-roam/org-roam-ui#92]
**When I click a node in the local graph, it does not expand**
The title pretty much contains it. I have set the UI to add the local graph of a node to the local graph when single clicked, but there is simply no reaction when clicking said node. 

I have tried setting double click etc., but no difference. 
I have pulled today's lates git version of ORUI.

**To Reproduce**
1. Open org-roam-ui
2. Click on active node to open local graph
3. Click a connected node in local graph

**Expected behavior**
The connected node expands, adding its local graph to the current local graph.

**Actual behavior**
No reaction to click.

**Screenshots**
N/A

**What browser were you using?**
Chromium

**Additional context**

**Comment by ThomasFKJorna** [comment]
Thanks for reporting this! I feel like I ran up against this issue myself once but dismissed it and then forgot about it. I do remember that expanding or adding to the local graph using the context menu *does* work, so for now you could try that while we figure this out.

**Comment by thriveth** [comment]
Thanks! Unfortunately, the context menu does not work for me either. Sendt fra min Galaxy
-------- Oprindelig besked --------Fra: "Thomas F. K. Jorna" ***@***.***> Dato: 01.10.2021  13.25  (GMT+01:00) Til: org-roam/org-roam-ui ***@***.***> Cc: Thøger Rivera-Thorsen ***@***.***>, Author ***@***.***> Emne: Re: [org-roam/org-roam-ui] [BUG] Nodes in local graph do not expand when clicked (#92) 
Thanks for reporting this! I feel like I ran up against this issue myself once but dismissed it and then forgot about it. I do remember that expanding or adding to the local graph using the context menu does work, so for now you could try that while we figure this out.

**Comment by MCSH** [comment]
I'm having this exact issue as well, any pointers where I should look to find out what's causing it?

**Comment by ThomasFKJorna** [comment]
There's not much you can personally do about it I'm afraid, this is an issue we need to resolve ourselves. Sorry for the inconvenience!

**Comment by ThomasFKJorna** [comment]
This should work again now! The issue was that I updated the filtering logic some time ago, but did not change the implementation in the expand feature. Let me know if it works for you!

**Comment by thriveth** [comment]
Thanks @ThomasFKJorna , I can confirm that it does indeed work again now, which makes me very happy!
